#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
cd "${SCRIPT_DIR}"

DEFAULT_NODES=(
  10.99.1.134
  10.99.0.117
  10.99.0.18
  10.99.0.227
  10.99.0.116
  10.99.0.165
  10.99.0.239
  10.99.0.167
)

usage() {
  cat <<'EOF'
Usage:
  BANK_NAME=<rollout_bank> CONTACT_EXPORT_NAME=<export_name> bash batch_distill_as_meshphys8.sh launch
  BANK_NAME=<rollout_bank> CONTACT_EXPORT_NAME=<export_name> bash batch_distill_as_meshphys8.sh check
  bash batch_distill_as_meshphys8.sh status
  bash batch_distill_as_meshphys8.sh stop

Useful env:
  NODES="node0 node1 ..."      override node list
  REMOTE_REPO=/home/ubuntu/FAR/holosoma
  SESSION=distill_as_meshphys_64gpu
  RUN_STAMP=<stamp>
  BANK_NAME=<required rollout bank under data/ds_as_data>
  CONTACT_EXPORT_NAME=<required contact export dir in BANK_NAME>
  PER_GPU_ENVS=1536            8 nodes x 8 GPUs x 1536 = 98304 global envs
  MASTER_ADDR=<node0>          default first node
  MASTER_PORT=29679
  NCCL_SOCKET_IFNAME=enp135s0  network interface for NCCL
  GLOO_SOCKET_IFNAME=enp135s0  network interface for Gloo
  NCCL_IB_DISABLE=1            force TCP socket path on these nodes
  NCCL_LIB_DIR=<path>          prepend runtime NCCL library directory
  BOX_RESUME_CKPT=<local init checkpoint>
  RESTART=1
  DRY_RUN=1
EOF
}

ACTION=${1:-status}
case "${ACTION}" in
  -h|--help|help)
    usage
    exit 0
    ;;
esac

if [[ "${ACTION}" == "launch" || "${ACTION}" == "check" ]]; then
  cat >&2 <<'EOF'
[ERROR] batch_distill_as_meshphys8.sh launch/check is quarantined.
This legacy controller does not pin/export the distributed runtime identity,
uses mutable remote source trees, and can report a successful check before the
real provenance/startup path runs. Use batch_ne.sh, whose snapshot, ownership,
runtime-manifest, checkpoint, and cross-rank provenance contracts are enforced.
EOF
  exit 2
fi

if [[ -n "${NODES:-}" ]]; then
  # shellcheck disable=SC2206
  NODE_LIST=(${NODES})
else
  NODE_LIST=("${DEFAULT_NODES[@]}")
fi
if [[ "${#NODE_LIST[@]}" -lt 1 ]]; then
  echo "[ERROR] Empty node list." >&2
  exit 2
fi

REMOTE_REPO=${REMOTE_REPO:-/home/ubuntu/FAR/holosoma}
SESSION=${SESSION:-distill_as_meshphys_64gpu}
RUN_STAMP=${RUN_STAMP:-$(date -u +%Y%m%d_%H%M%S)}
BANK_NAME=${BANK_NAME:-}
CONTACT_EXPORT_NAME=${CONTACT_EXPORT_NAME:-}
SOLID_TARGET_BANK_NAME=${SOLID_TARGET_BANK_NAME:-${BANK_NAME:+${BANK_NAME}_distill_solid_box_bin_barrel_ball}}
PER_GPU_ENVS=${PER_GPU_ENVS:-1536}
CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
NPROC=${NPROC:-8}
NNODES=${NNODES:-${#NODE_LIST[@]}}
MASTER_ADDR=${MASTER_ADDR:-${NODE_LIST[0]}}
MASTER_PORT=${MASTER_PORT:-29679}
NCCL_SOCKET_IFNAME=${NCCL_SOCKET_IFNAME:-enp135s0}
GLOO_SOCKET_IFNAME=${GLOO_SOCKET_IFNAME:-${NCCL_SOCKET_IFNAME}}
NCCL_IB_DISABLE=${NCCL_IB_DISABLE:-1}
NCCL_DEBUG=${NCCL_DEBUG:-WARN}
TORCH_NCCL_ASYNC_ERROR_HANDLING=${TORCH_NCCL_ASYNC_ERROR_HANDLING:-1}
HOLOSOMA_DEBUG_HEARTBEAT=${HOLOSOMA_DEBUG_HEARTBEAT:-0}
NCCL_LIB_DIR=${NCCL_LIB_DIR:-/home/ubuntu/.holosoma_deps/miniconda3/envs/hssim/lib/python3.11/site-packages/nvidia/nccl/lib}
RESTART=${RESTART:-1}
DRY_RUN=${DRY_RUN:-0}
SSH_OPTS=${SSH_OPTS:-"-o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10"}
PYTHON_BIN=${PYTHON_BIN:-/home/ubuntu/.holosoma_deps/miniconda3/envs/hssim/bin/python3.11}
BOX_RESUME_CKPT=${BOX_RESUME_CKPT:-/home/ubuntu/.cache/holosoma/checkpoints/as_ch51_convex_pretrain_model_22000.pt}
RUN_NAME=${RUN_NAME:-g1_w_object_distill_as_button_solid_meshphys_rollout67000_64gpu_init_box}
TRAINING_NAME=${TRAINING_NAME:-g1_29dof_wbt_w_object_distill_as_button_solid_meshphys_rollout67000_64gpu_depth}
SCHEDULE_NAME=${SCHEDULE_NAME:-as_meshphys_rollout67000_sparse_root_ppo_first_contact_drop_button_solid}
SCHEDULE_NOTES=${SCHEDULE_NOTES:-64-GPU AS solid distillation from mesh-physics teacher rollout contacts. Object geometry and URDF inertia come from the mesh-physics bank; contact points are regenerated by the AS teacher rollout.}
NUM_LEARNING_ITERATIONS=${NUM_LEARNING_ITERATIONS:-40000}
SAVE_INTERVAL=${SAVE_INTERVAL:-500}

if [[ "${ACTION}" == "launch" || "${ACTION}" == "check" ]]; then
  if [[ -z "${BANK_NAME}" ]]; then
    echo "[ERROR] BANK_NAME is required for ${ACTION}." >&2
    exit 2
  fi
  if [[ -z "${CONTACT_EXPORT_NAME}" ]]; then
    echo "[ERROR] CONTACT_EXPORT_NAME is required for ${ACTION}." >&2
    exit 2
  fi
fi
if ! [[ "${PER_GPU_ENVS}" =~ ^[0-9]+$ ]] || (( PER_GPU_ENVS < 1 )); then
  echo "[ERROR] PER_GPU_ENVS must be a positive integer. Got: ${PER_GPU_ENVS}" >&2
  exit 2
fi
if ! [[ "${NNODES}" =~ ^[0-9]+$ ]] || (( NNODES != ${#NODE_LIST[@]} )); then
  echo "[ERROR] NNODES must equal node list length. Got NNODES=${NNODES}, nodes=${#NODE_LIST[@]}" >&2
  exit 2
fi

TOTAL_NUM_ENVS=$((PER_GPU_ENVS * NPROC * NNODES))
LOG_DIR="logs/batch_meshphys/${SESSION}_${RUN_STAMP}"

quote() {
  printf '%q' "$1"
}

remote_run() {
  local node="$1"
  local cmd="$2"
  if [[ "${DRY_RUN}" == "1" ]]; then
    printf '[DRY_RUN] ssh %s %s\n' "${node}" "${cmd}"
    return 0
  fi
  # shellcheck disable=SC2086
  ssh ${SSH_OPTS} "${node}" "${cmd}"
}

remote_env_exports() {
  local node_rank="$1"
  cat <<EOF
export CUDA_VISIBLE_DEVICES=$(quote "${CUDA_VISIBLE_DEVICES}")
export OMNI_KIT_ACCEPT_EULA=YES
export ACCEPT_EULA=Y
export PYTHON_BIN=$(quote "${PYTHON_BIN}")
export NPROC=$(quote "${NPROC}")
export NNODES=$(quote "${NNODES}")
export NODE_RANK=$(quote "${node_rank}")
export MASTER_ADDR=$(quote "${MASTER_ADDR}")
export MASTER_PORT=$(quote "${MASTER_PORT}")
export NCCL_SOCKET_IFNAME=$(quote "${NCCL_SOCKET_IFNAME}")
export GLOO_SOCKET_IFNAME=$(quote "${GLOO_SOCKET_IFNAME}")
export NCCL_IB_DISABLE=$(quote "${NCCL_IB_DISABLE}")
export NCCL_DEBUG=$(quote "${NCCL_DEBUG}")
export TORCH_NCCL_ASYNC_ERROR_HANDLING=$(quote "${TORCH_NCCL_ASYNC_ERROR_HANDLING}")
export HOLOSOMA_DEBUG_HEARTBEAT=$(quote "${HOLOSOMA_DEBUG_HEARTBEAT}")
export NCCL_LIB_DIR=$(quote "${NCCL_LIB_DIR}")
export LD_LIBRARY_PATH=$(quote "${NCCL_LIB_DIR}")\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}
export PER_GPU_ENVS=$(quote "${PER_GPU_ENVS}")
export AS_SUCCESS133_FINAL0P5=1
export AS_RANK_LOCAL_SHARDS=1
export AS_SUCCESS133_BANK_NAME=$(quote "${BANK_NAME}")
export CORL_SOLID80_BANK_NAME=$(quote "${BANK_NAME}")
export OMOMO_DATA_DIR=$(quote "${REMOTE_REPO}/data/ds_as_data/${BANK_NAME}")
export OMOMO_OBJECT_MAP=$(quote "${REMOTE_REPO}/data/ds_as_data/${BANK_NAME}/_clip_object_urdf_map.json")
export SOLID_CONTACT_EXPORT_NAME=$(quote "${CONTACT_EXPORT_NAME}")
export AS_CONTACT_EXPORT_ROOT=$(quote "${REMOTE_REPO}/data/ds_as_data/${BANK_NAME}/${CONTACT_EXPORT_NAME}")
export SOLID_TARGET_BANK_NAME=$(quote "${SOLID_TARGET_BANK_NAME}")
export RESUME_FROM_BOX=1
export BOX_RESUME_CKPT=$(quote "${BOX_RESUME_CKPT}")
export RESUME_FROM_BOX_CKPT=$(quote "${BOX_RESUME_CKPT}")
export POLICY_INIT_CKPT=$(quote "${BOX_RESUME_CKPT}")
export RUN_NAME=$(quote "${RUN_NAME}")
export TRAINING_NAME=$(quote "${TRAINING_NAME}")
export SCHEDULE_NAME=$(quote "${SCHEDULE_NAME}")
export SCHEDULE_NOTES=$(quote "${SCHEDULE_NOTES}")
export NUM_LEARNING_ITERATIONS=$(quote "${NUM_LEARNING_ITERATIONS}")
export SAVE_INTERVAL=$(quote "${SAVE_INTERVAL}")
export OBJECT_GEOMETRY_MODE=mesh
export HOLOSOMA_OBJECT_SPAWN_MODE=single_slot_multi_urdf
export WANDB_RESUME_SAME_RUN=0
export PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY=${PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY:-301989888}
export PHYSX_GPU_FOUND_LOST_AGGREGATE_PAIRS_CAPACITY=${PHYSX_GPU_FOUND_LOST_AGGREGATE_PAIRS_CAPACITY:-436207616}
export PHYSX_GPU_TOTAL_AGGREGATE_PAIRS_CAPACITY=${PHYSX_GPU_TOTAL_AGGREGATE_PAIRS_CAPACITY:-134217728}
export PHYSX_GPU_COLLISION_STACK_SIZE=${PHYSX_GPU_COLLISION_STACK_SIZE:-268435456}
EOF
}

check_node() {
  local node="$1"
  local cmd
  cmd=$(cat <<EOF
set -euo pipefail
cd $(quote "${REMOTE_REPO}")
$(remote_env_exports 0)
source ./scripts/gpu_launch_defaults.sh
test -d "\${OMOMO_DATA_DIR}"
test -f "\${OMOMO_OBJECT_MAP}"
test -d "\${AS_CONTACT_EXPORT_ROOT}/clips"
test -f "\${BOX_RESUME_CKPT}"
CHECK_ONLY=1 bash distill_as_button_solid.sh
EOF
)
  remote_run "${node}" "${cmd}"
}

launch_node() {
  local node="$1"
  local node_rank="$2"
  local log_file="${REMOTE_REPO}/${LOG_DIR}/node_${node_rank}_${node}.log"
  local train_cmd
  train_cmd=$(cat <<EOF
set -euo pipefail
cd $(quote "${REMOTE_REPO}")
mkdir -p $(quote "${REMOTE_REPO}/${LOG_DIR}")
$(remote_env_exports "${node_rank}")
source ./scripts/gpu_launch_defaults.sh
echo "[INFO][${node}] session=${SESSION} node_rank=${node_rank}/${NNODES} per_gpu_envs=${PER_GPU_ENVS} total_num_envs=${TOTAL_NUM_ENVS}"
echo "[INFO][${node}] bank=${BANK_NAME} contact_export=${CONTACT_EXPORT_NAME}"
echo "[INFO][${node}] master=${MASTER_ADDR}:${MASTER_PORT} log=${log_file}"
echo "[INFO][${node}] nccl_if=${NCCL_SOCKET_IFNAME} gloo_if=${GLOO_SOCKET_IFNAME} nccl_ib_disable=${NCCL_IB_DISABLE}"
echo "[INFO][${node}] nccl_lib_dir=${NCCL_LIB_DIR}"
exec bash distill_as_button_solid.sh 2>&1 | tee $(quote "${log_file}")
EOF
)
  local cmd
  cmd=$(cat <<EOF
set -euo pipefail
cd $(quote "${REMOTE_REPO}")
mkdir -p $(quote "${REMOTE_REPO}/${LOG_DIR}")
if tmux has-session -t $(quote "${SESSION}") 2>/dev/null; then
  if [[ $(quote "${RESTART}") == "1" ]]; then
    tmux kill-session -t $(quote "${SESSION}")
  else
    echo "[ERROR][${node}] tmux session already exists: ${SESSION}" >&2
    exit 1
  fi
fi
tmux new-session -d -s $(quote "${SESSION}") $(quote "${train_cmd}")
tmux display-message -p -t $(quote "${SESSION}") "[INFO][${node}] started #{session_name}"
EOF
)
  remote_run "${node}" "${cmd}"
}

status_node() {
  local node="$1"
  local cmd
  cmd=$(cat <<EOF
set -euo pipefail
cd $(quote "${REMOTE_REPO}")
echo "===== ${node} ====="
tmux has-session -t $(quote "${SESSION}") 2>/dev/null && tmux list-sessions | grep -F $(quote "${SESSION}") || echo "tmux:${SESSION}:not-running"
latest_log=\$(ls -1t logs/batch_meshphys/${SESSION}_*/node_*_${node}.log 2>/dev/null | head -1 || true)
if [[ -n "\${latest_log}" ]]; then
  echo "log=\${latest_log}"
  tail -50 "\${latest_log}"
fi
EOF
)
  remote_run "${node}" "${cmd}"
}

stop_node() {
  local node="$1"
  local cmd
  cmd=$(cat <<EOF
set -euo pipefail
if tmux has-session -t $(quote "${SESSION}") 2>/dev/null; then
  tmux kill-session -t $(quote "${SESSION}")
  echo "[INFO][${node}] stopped ${SESSION}"
else
  echo "[INFO][${node}] ${SESSION} not running"
fi
EOF
)
  remote_run "${node}" "${cmd}"
}

run_check() {
  local pids=()
  local failed=0
  for node in "${NODE_LIST[@]}"; do
    check_node "${node}" &
    pids+=("$!")
  done
  for pid in "${pids[@]}"; do
    if ! wait "${pid}"; then
      failed=1
    fi
  done
  if (( failed != 0 )); then
    echo "[ERROR] One or more nodes failed check." >&2
    exit 1
  fi
}

run_launch() {
  echo "[INFO] Launching ${NNODES} nodes x ${NPROC} GPUs, PER_GPU_ENVS=${PER_GPU_ENVS}, TOTAL_NUM_ENVS=${TOTAL_NUM_ENVS}"
  local rank=0
  for node in "${NODE_LIST[@]}"; do
    echo "[INFO] Launching ${node} node_rank=${rank}"
    launch_node "${node}" "${rank}"
    rank=$((rank + 1))
  done
}

case "${ACTION}" in
  check)
    run_check
    ;;
  launch)
    run_launch
    ;;
  status)
    for node in "${NODE_LIST[@]}"; do
      status_node "${node}" || true
    done
    ;;
  stop)
    for node in "${NODE_LIST[@]}"; do
      stop_node "${node}" || true
    done
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
