#!/usr/bin/env bash
set -euo pipefail

# Pure-RL bootstrap launcher.
#
# This wrapper keeps the base debug_pure_rl.sh strict behavior:
#   - no distillation
#   - no teacher policy
#   - no checkpoint/policy initialization
#   - no silent geometry fallback
#
# The defaults here are intentionally easier than the final task. They are meant
# to keep PPO episodes alive long enough to learn locomotion and pickup before
# tightening termination/contact conditions in an explicitly chosen later stage.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
cd "${SCRIPT_DIR}"

STAGE_RAW=${PURE_RL_BOOTSTRAP_STAGE:-A}
STAGE=$(printf '%s' "${STAGE_RAW}" | tr '[:lower:]' '[:upper:]')
case "${STAGE}" in
  A|BOOTSTRAP)
    STAGE=A
    PURE_RL_BAD_REF_POS_THRESHOLD=${PURE_RL_BAD_REF_POS_THRESHOLD:-1.0}
    PURE_RL_BAD_REF_ORI_THRESHOLD=${PURE_RL_BAD_REF_ORI_THRESHOLD:-1.5}
    PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD=${PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD:-0.5}
    PURE_RL_BAD_OBJECT_POS_THRESHOLD=${PURE_RL_BAD_OBJECT_POS_THRESHOLD:-1.0}
    PURE_RL_BAD_OBJECT_ORI_THRESHOLD=${PURE_RL_BAD_OBJECT_ORI_THRESHOLD:-1.5}
    PURE_RL_WRIST_WEIGHT=${PURE_RL_WRIST_WEIGHT:-1.0}
    PURE_RL_CONTACT_WEIGHT=${PURE_RL_CONTACT_WEIGHT:-1.5}
    PURE_RL_CONTACT_USE_FORCE_TERM=${PURE_RL_CONTACT_USE_FORCE_TERM:-False}
    PURE_RL_CONTACT_FORCE_GATE_MODE=${PURE_RL_CONTACT_FORCE_GATE_MODE:-soft}
    PURE_RL_REQUIRE_STABLE_CONTACT=${PURE_RL_REQUIRE_STABLE_CONTACT:-False}
    PURE_RL_USE_CONTACT_SCHEDULE=${PURE_RL_USE_CONTACT_SCHEDULE:-True}
    PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS=${PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS:-15}
    PURE_RL_POSITION_SIGMA=${PURE_RL_POSITION_SIGMA:-0.12}
    PURE_RL_PUSH_INTERVAL_S=${PURE_RL_PUSH_INTERVAL_S:-'[1000000.0,1000001.0]'}
    PURE_RL_PUSH_MAX_VEL=${PURE_RL_PUSH_MAX_VEL:-'[0.0,0.0,0.0,0.0,0.0,0.0]'}
    ;;
  B|TIGHTEN)
    STAGE=B
    PURE_RL_BAD_REF_POS_THRESHOLD=${PURE_RL_BAD_REF_POS_THRESHOLD:-0.75}
    PURE_RL_BAD_REF_ORI_THRESHOLD=${PURE_RL_BAD_REF_ORI_THRESHOLD:-1.2}
    PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD=${PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD:-0.35}
    PURE_RL_BAD_OBJECT_POS_THRESHOLD=${PURE_RL_BAD_OBJECT_POS_THRESHOLD:-0.6}
    PURE_RL_BAD_OBJECT_ORI_THRESHOLD=${PURE_RL_BAD_OBJECT_ORI_THRESHOLD:-1.2}
    PURE_RL_WRIST_WEIGHT=${PURE_RL_WRIST_WEIGHT:-2.0}
    PURE_RL_CONTACT_WEIGHT=${PURE_RL_CONTACT_WEIGHT:-3.0}
    PURE_RL_CONTACT_USE_FORCE_TERM=${PURE_RL_CONTACT_USE_FORCE_TERM:-False}
    PURE_RL_CONTACT_FORCE_GATE_MODE=${PURE_RL_CONTACT_FORCE_GATE_MODE:-soft}
    PURE_RL_REQUIRE_STABLE_CONTACT=${PURE_RL_REQUIRE_STABLE_CONTACT:-False}
    PURE_RL_USE_CONTACT_SCHEDULE=${PURE_RL_USE_CONTACT_SCHEDULE:-True}
    PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS=${PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS:-10}
    PURE_RL_POSITION_SIGMA=${PURE_RL_POSITION_SIGMA:-0.10}
    PURE_RL_PUSH_INTERVAL_S=${PURE_RL_PUSH_INTERVAL_S:-'[1000000.0,1000001.0]'}
    PURE_RL_PUSH_MAX_VEL=${PURE_RL_PUSH_MAX_VEL:-'[0.0,0.0,0.0,0.0,0.0,0.0]'}
    ;;
  C|FINAL|FULL)
    STAGE=C
    PURE_RL_BAD_REF_POS_THRESHOLD=${PURE_RL_BAD_REF_POS_THRESHOLD:-0.5}
    PURE_RL_BAD_REF_ORI_THRESHOLD=${PURE_RL_BAD_REF_ORI_THRESHOLD:-0.8}
    PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD=${PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD:-0.25}
    PURE_RL_BAD_OBJECT_POS_THRESHOLD=${PURE_RL_BAD_OBJECT_POS_THRESHOLD:-0.25}
    PURE_RL_BAD_OBJECT_ORI_THRESHOLD=${PURE_RL_BAD_OBJECT_ORI_THRESHOLD:-0.8}
    PURE_RL_WRIST_WEIGHT=${PURE_RL_WRIST_WEIGHT:-4.0}
    PURE_RL_CONTACT_WEIGHT=${PURE_RL_CONTACT_WEIGHT:-7.0}
    PURE_RL_CONTACT_USE_FORCE_TERM=${PURE_RL_CONTACT_USE_FORCE_TERM:-True}
    PURE_RL_CONTACT_FORCE_GATE_MODE=${PURE_RL_CONTACT_FORCE_GATE_MODE:-binary}
    PURE_RL_REQUIRE_STABLE_CONTACT=${PURE_RL_REQUIRE_STABLE_CONTACT:-True}
    PURE_RL_USE_CONTACT_SCHEDULE=${PURE_RL_USE_CONTACT_SCHEDULE:-True}
    PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS=${PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS:-5}
    PURE_RL_POSITION_SIGMA=${PURE_RL_POSITION_SIGMA:-0.08}
    PURE_RL_PUSH_INTERVAL_S=${PURE_RL_PUSH_INTERVAL_S:-'[0.5,2.0]'}
    PURE_RL_PUSH_MAX_VEL=${PURE_RL_PUSH_MAX_VEL:-'[0.7,0.7,0.25,0.7,0.7,1.0]'}
    ;;
  *)
    echo "[ERROR] Unsupported PURE_RL_BOOTSTRAP_STAGE='${STAGE_RAW}'. Use A, B, or C." >&2
    exit 2
    ;;
esac

NPROC=${NPROC:-1}
NNODES=${NNODES:-1}
RUN_STAMP=${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}

export NPROC
export NNODES
export RUN_STAMP
export PER_GPU_ENVS=${PER_GPU_ENVS:-2048}
export NUM_MINI_BATCHES=${NUM_MINI_BATCHES:-$((NPROC * NNODES))}
export NUM_LEARNING_EPOCHS=${NUM_LEARNING_EPOCHS:-2}
export ACTOR_LR=${ACTOR_LR:-3e-4}
export CRITIC_LR=${CRITIC_LR:-3e-4}
export INIT_NOISE_STD=${INIT_NOISE_STD:-0.25}
export ACTOR_MIN_NOISE_STD=${ACTOR_MIN_NOISE_STD:-0.02}
export ENTROPY_COEF=${ENTROPY_COEF:-0.0}
export CLIP_PARAM=${CLIP_PARAM:-0.1}
export MAX_GRAD_NORM=${MAX_GRAD_NORM:-0.5}
export PPO_SCHEDULE=${PPO_SCHEDULE:-fixed}
export HOLOSOMA_GLOO_SMALL_COLLECTIVES=${HOLOSOMA_GLOO_SMALL_COLLECTIVES:-1}
export HOLOSOMA_GLOO_GRAD_REDUCE=${HOLOSOMA_GLOO_GRAD_REDUCE:-1}
export HOLOSOMA_SYNC_AFTER_GRAD_ALLREDUCE=${HOLOSOMA_SYNC_AFTER_GRAD_ALLREDUCE:-1}
export HOLOSOMA_SYNC_EACH_ITERATION=${HOLOSOMA_SYNC_EACH_ITERATION:-0}
export HOLOSOMA_GLOO_BARRIER=${HOLOSOMA_GLOO_BARRIER:-0}
export START_AT_TIMESTEP_ZERO_PROB=${START_AT_TIMESTEP_ZERO_PROB:-1.0}
export RESET_NOISE_SCALE=${RESET_NOISE_SCALE:-0.25}
export USE_ADAPTIVE_TIMESTEPS_SAMPLER=${USE_ADAPTIVE_TIMESTEPS_SAMPLER:-False}
export ENABLE_CLEAN_NOISY_CURRICULUM=${ENABLE_CLEAN_NOISY_CURRICULUM:-0}
export RUN_NAME=${RUN_NAME:-debug_pure_rl_bootstrap_stage${STAGE}_as_button_solid_prism_debug30_bigmlp_${RUN_STAMP}}
export TRAINING_NAME=${TRAINING_NAME:-debug_pure_rl_bootstrap_stage${STAGE}_as_button_solid_prism_debug30_bigmlp_${RUN_STAMP}}
export BAD_REF_POS_THRESHOLD=${BAD_REF_POS_THRESHOLD:-${PURE_RL_BAD_REF_POS_THRESHOLD}}
export BAD_REF_ORI_THRESHOLD=${BAD_REF_ORI_THRESHOLD:-${PURE_RL_BAD_REF_ORI_THRESHOLD}}
export BAD_MOTION_BODY_POS_THRESHOLD=${BAD_MOTION_BODY_POS_THRESHOLD:-${PURE_RL_BAD_MOTION_BODY_POS_THRESHOLD}}
export BAD_OBJECT_POS_THRESHOLD=${BAD_OBJECT_POS_THRESHOLD:-${PURE_RL_BAD_OBJECT_POS_THRESHOLD}}
export BAD_OBJECT_ORI_THRESHOLD=${BAD_OBJECT_ORI_THRESHOLD:-${PURE_RL_BAD_OBJECT_ORI_THRESHOLD}}
export PUSH_INTERVAL_S=${PUSH_INTERVAL_S:-${PURE_RL_PUSH_INTERVAL_S}}
export PUSH_MAX_VEL=${PUSH_MAX_VEL:-${PURE_RL_PUSH_MAX_VEL}}

bootstrap_args=(
  --algo.config.schedule="${PPO_SCHEDULE}"
  --reward.terms.offline-contact-guidance.params.wrist-weight="${PURE_RL_WRIST_WEIGHT}"
  --reward.terms.offline-contact-guidance.params.contact-weight="${PURE_RL_CONTACT_WEIGHT}"
  --reward.terms.offline-contact-guidance.params.use-force-term="${PURE_RL_CONTACT_USE_FORCE_TERM}"
  --reward.terms.offline-contact-guidance.params.force-gate-mode="${PURE_RL_CONTACT_FORCE_GATE_MODE}"
  --reward.terms.offline-contact-guidance.params.require-stable-contact="${PURE_RL_REQUIRE_STABLE_CONTACT}"
  --reward.terms.offline-contact-guidance.params.use-contact-schedule="${PURE_RL_USE_CONTACT_SCHEDULE}"
  --reward.terms.offline-contact-guidance.params.contact-schedule-relax-steps="${PURE_RL_CONTACT_SCHEDULE_RELAX_STEPS}"
  --reward.terms.offline-contact-guidance.params.position-sigma="${PURE_RL_POSITION_SIGMA}"
)

echo "[INFO] pure_rl_bootstrap_stage=${STAGE}"
echo "[INFO] learning_rate actor=${ACTOR_LR} critic=${CRITIC_LR} schedule=${PPO_SCHEDULE}"
echo "[INFO] optimizer num_learning_epochs=${NUM_LEARNING_EPOCHS} num_mini_batches=${NUM_MINI_BATCHES} clip_param=${CLIP_PARAM} max_grad_norm=${MAX_GRAD_NORM}"
echo "[INFO] distributed gloo_small_collectives=${HOLOSOMA_GLOO_SMALL_COLLECTIVES:-unset} gloo_grad_reduce=${HOLOSOMA_GLOO_GRAD_REDUCE:-unset} sync_after_grad_allreduce=${HOLOSOMA_SYNC_AFTER_GRAD_ALLREDUCE:-unset} sync_each_iteration=${HOLOSOMA_SYNC_EACH_ITERATION:-unset} gloo_barrier=${HOLOSOMA_GLOO_BARRIER:-unset}"
echo "[INFO] exploration init_noise_std=${INIT_NOISE_STD} min_noise_std=${ACTOR_MIN_NOISE_STD} entropy_coef=${ENTROPY_COEF}"
echo "[INFO] sampling start_at_timestep_zero_prob=${START_AT_TIMESTEP_ZERO_PROB} reset_noise_scale=${RESET_NOISE_SCALE} adaptive_sampler=${USE_ADAPTIVE_TIMESTEPS_SAMPLER}"
echo "[INFO] termination bad_ref_pos=${BAD_REF_POS_THRESHOLD} bad_ref_ori=${BAD_REF_ORI_THRESHOLD} bad_body_pos=${BAD_MOTION_BODY_POS_THRESHOLD} bad_object_pos=${BAD_OBJECT_POS_THRESHOLD} bad_object_ori=${BAD_OBJECT_ORI_THRESHOLD}"
echo "[INFO] contact wrist_weight=${PURE_RL_WRIST_WEIGHT} contact_weight=${PURE_RL_CONTACT_WEIGHT} use_force=${PURE_RL_CONTACT_USE_FORCE_TERM} gate=${PURE_RL_CONTACT_FORCE_GATE_MODE} schedule=${PURE_RL_USE_CONTACT_SCHEDULE} position_sigma=${PURE_RL_POSITION_SIGMA}"
echo "[INFO] push interval=${PUSH_INTERVAL_S} max_vel=${PUSH_MAX_VEL}"

exec bash "${SCRIPT_DIR}/debug_pure_rl.sh" "${bootstrap_args[@]}" "$@"
