#!/usr/bin/env bash
set -euo pipefail

# Distill object-carry generalist -> sparse-root student with mocap-access box state.
#
# This launcher intentionally mirrors distill_box_perception.sh for:
# - teacher compatibility handling
# - rollout-ref / success-filtered motion-bank selection
# - PPO+DAgger schedule variants
# - distributed launch behavior
#
# The only student-facing difference is observation:
# - actor_obs_root: root command
# - actor_obs_proprio_no_linvel: proprioception without base linear velocity
# - actor_obs_actions: single-step past action only
# - actor_obs_box: current object [pos(3), rot6d(6), size(3)]

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "${SCRIPT_DIR}"

DEFAULT_TEACHER_CHECKPOINT=${DEFAULT_TEACHER_CHECKPOINT:-"wandb://zihanw22/boxer/u5lguxvl/model_17000.pt"}
TEACHER_CHECKPOINT=${TEACHER_CHECKPOINT:-${DEFAULT_TEACHER_CHECKPOINT}}

CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1}
if [[ -z "${NPROC:-}" ]]; then
  IFS=',' read -r -a _visible_gpus <<< "${CUDA_VISIBLE_DEVICES}"
  NPROC=${#_visible_gpus[@]}
fi
PER_GPU_ENVS=${PER_GPU_ENVS:-2048}
NUM_ENVS=${NUM_ENVS:-$((PER_GPU_ENVS * NPROC))}

DATA_MODE=${DATA_MODE:-pure-sd}
TRACKER_PROFILE=${TRACKER_PROFILE:-old-tracker}
SCHEDULE_VARIANT=${SCHEDULE_VARIANT:-ppo_first}
EXP=${EXP:-g1-29dof-wbt-w-object-distill-sparse-root-cmd-r2s-rollout-ref}
RUN_NAME=${RUN_NAME:-g1_w_object_distill_box_mocap_sparse_root_cmd_r2s_rollout_ref}
TRAINING_NAME=${TRAINING_NAME:-g1_29dof_wbt_w_object_distill_box_mocap_sparse_root_cmd_r2s_rollout_ref_access_to_box_state}
TRAINING_PROJECT=${TRAINING_PROJECT:-boxer}

PERCEPTION_PRESET=${PERCEPTION_PRESET:-none}
CRITIC_PERCEPTION_PRESET=${CRITIC_PERCEPTION_PRESET:-none}
PERCEPTION_INTO_CRITIC_MODULES=${PERCEPTION_INTO_CRITIC_MODULES:-False}
CAMERA_PITCH_DEG=${CAMERA_PITCH_DEG-}
STUDENT_ACTOR_INPUTS=${STUDENT_ACTOR_INPUTS:-"['actor_obs_root','actor_obs_proprio_no_linvel','actor_obs_actions','actor_obs_box']"}

DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES=${DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES:-False}
DAGGER_IGNORE_EPISODE_INITIAL_STEPS=${DAGGER_IGNORE_EPISODE_INITIAL_STEPS:-0}
PPO_START_EPOCH=${PPO_START_EPOCH:-0}
DAGGER_END_EPOCH=${DAGGER_END_EPOCH:-4000}
PPO_START_COEFF=${PPO_START_COEFF:-0.1}
PPO_TARGET_COEFF=${PPO_TARGET_COEFF:-0.9}
PPO_SCHEDULE_STEP_EPOCHS=${PPO_SCHEDULE_STEP_EPOCHS:-500}
PPO_START_NOISE_STD=${PPO_START_NOISE_STD:-0.1}
PPO_START_NOISE_STD_UNTIL_COEFF=${PPO_START_NOISE_STD_UNTIL_COEFF:-0.1}
DAGGER_LOSS_COEF=${DAGGER_LOSS_COEF:-1.0}
BC_LOSS_COEF=${BC_LOSS_COEF:-1.0}
TEACHER_ACTION_MIX_RATIO=${TEACHER_ACTION_MIX_RATIO:-0.0}
NUM_LEARNING_ITERATIONS=${NUM_LEARNING_ITERATIONS:-40000}
SPARSE_GOAL_ENABLED=${SPARSE_GOAL_ENABLED:-False}
START_AT_TIMESTEP_ZERO_PROB=${START_AT_TIMESTEP_ZERO_PROB:-0.2}
START_AT_TIMESTEP_ZERO_PROB_END=${START_AT_TIMESTEP_ZERO_PROB_END:-1.0}
START_AT_TIMESTEP_ZERO_PROB_START_ITER=${START_AT_TIMESTEP_ZERO_PROB_START_ITER:-2500}
FREEZE_AT_TIMESTEP_ZERO_PROB=${FREEZE_AT_TIMESTEP_ZERO_PROB:-0.0}
FREEZE_AT_TIMESTEP_ZERO_PROB_END=${FREEZE_AT_TIMESTEP_ZERO_PROB_END:-0.0}
FREEZE_AT_TIMESTEP_ZERO_PROB_START_ITER=${FREEZE_AT_TIMESTEP_ZERO_PROB_START_ITER:-2500}
ENABLE_DEFAULT_POSE_PREPEND=${ENABLE_DEFAULT_POSE_PREPEND:-False}
DEFAULT_POSE_PREPEND_DURATION_S=${DEFAULT_POSE_PREPEND_DURATION_S:-0.0}
RESET_TO_DEFAULT_POSE=${RESET_TO_DEFAULT_POSE:-False}
VISER_DISTILL_MINIMAL_UI=${VISER_DISTILL_MINIMAL_UI:-1}
VISER_SHOW_TARGET_KEYPOINTS=${VISER_SHOW_TARGET_KEYPOINTS:-0}

SCHEDULE_NAME=${SCHEDULE_NAME:-sparse_root_teacher_anchor_v4_ppo_first_step_mix_mocap}
SCHEDULE_NOTES=${SCHEDULE_NOTES:-"Mocap box-state student. PPO and DAgger are both active from iteration 0. PPO starts at 0.1 and increases by 0.1 every 500 iterations until 0.9 at 4000; effective DAgger weight decreases from 0.9 to 0.1. Student observes root command, proprio, past action, and current object pose/scale."}

echo "[INFO] distill mode: mocap-access-to-box"
echo "[INFO] teacher_checkpoint=${TEACHER_CHECKPOINT}"
echo "[INFO] cuda_visible_devices=${CUDA_VISIBLE_DEVICES} nproc=${NPROC} per_gpu_envs=${PER_GPU_ENVS} total_envs=${NUM_ENVS}"
echo "[INFO] data_mode=${DATA_MODE} tracker_profile=${TRACKER_PROFILE} schedule_variant=${SCHEDULE_VARIANT}"
echo "[INFO] student_actor_inputs=${STUDENT_ACTOR_INPUTS}"
echo "[INFO] perception_preset=${PERCEPTION_PRESET} critic_perception_preset=${CRITIC_PERCEPTION_PRESET}"
echo "[INFO] ppo_schedule=${PPO_START_EPOCH}->${DAGGER_END_EPOCH} start=${PPO_START_COEFF} target=${PPO_TARGET_COEFF} step_epochs=${PPO_SCHEDULE_STEP_EPOCHS}"
echo "[INFO] ppo_start_noise_std=${PPO_START_NOISE_STD} until_coeff=${PPO_START_NOISE_STD_UNTIL_COEFF}"
echo "[INFO] dagger_ignore_external_goal_samples=${DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES}"
echo "[INFO] sparse_goal_enabled=${SPARSE_GOAL_ENABLED}"

exec env \
  DEFAULT_TEACHER_CHECKPOINT="${DEFAULT_TEACHER_CHECKPOINT}" \
  TEACHER_CHECKPOINT="${TEACHER_CHECKPOINT}" \
  CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}" \
  NPROC="${NPROC}" \
  PER_GPU_ENVS="${PER_GPU_ENVS}" \
  NUM_ENVS="${NUM_ENVS}" \
  DATA_MODE="${DATA_MODE}" \
  TRACKER_PROFILE="${TRACKER_PROFILE}" \
  SCHEDULE_VARIANT="${SCHEDULE_VARIANT}" \
  EXP="${EXP}" \
  RUN_NAME="${RUN_NAME}" \
  TRAINING_NAME="${TRAINING_NAME}" \
  TRAINING_PROJECT="${TRAINING_PROJECT}" \
  PERCEPTION_PRESET="${PERCEPTION_PRESET}" \
  CRITIC_PERCEPTION_PRESET="${CRITIC_PERCEPTION_PRESET}" \
  PERCEPTION_INTO_CRITIC_MODULES="${PERCEPTION_INTO_CRITIC_MODULES}" \
  CAMERA_PITCH_DEG="${CAMERA_PITCH_DEG}" \
  STUDENT_ACTOR_INPUTS="${STUDENT_ACTOR_INPUTS}" \
  DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES="${DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES}" \
  DAGGER_IGNORE_EPISODE_INITIAL_STEPS="${DAGGER_IGNORE_EPISODE_INITIAL_STEPS}" \
  PPO_START_EPOCH="${PPO_START_EPOCH}" \
  DAGGER_END_EPOCH="${DAGGER_END_EPOCH}" \
  PPO_START_COEFF="${PPO_START_COEFF}" \
  PPO_TARGET_COEFF="${PPO_TARGET_COEFF}" \
  PPO_SCHEDULE_STEP_EPOCHS="${PPO_SCHEDULE_STEP_EPOCHS}" \
  PPO_START_NOISE_STD="${PPO_START_NOISE_STD}" \
  PPO_START_NOISE_STD_UNTIL_COEFF="${PPO_START_NOISE_STD_UNTIL_COEFF}" \
  DAGGER_LOSS_COEF="${DAGGER_LOSS_COEF}" \
  BC_LOSS_COEF="${BC_LOSS_COEF}" \
  TEACHER_ACTION_MIX_RATIO="${TEACHER_ACTION_MIX_RATIO}" \
  NUM_LEARNING_ITERATIONS="${NUM_LEARNING_ITERATIONS}" \
  SPARSE_GOAL_ENABLED="${SPARSE_GOAL_ENABLED}" \
  START_AT_TIMESTEP_ZERO_PROB="${START_AT_TIMESTEP_ZERO_PROB}" \
  START_AT_TIMESTEP_ZERO_PROB_END="${START_AT_TIMESTEP_ZERO_PROB_END}" \
  START_AT_TIMESTEP_ZERO_PROB_START_ITER="${START_AT_TIMESTEP_ZERO_PROB_START_ITER}" \
  FREEZE_AT_TIMESTEP_ZERO_PROB="${FREEZE_AT_TIMESTEP_ZERO_PROB}" \
  FREEZE_AT_TIMESTEP_ZERO_PROB_END="${FREEZE_AT_TIMESTEP_ZERO_PROB_END}" \
  FREEZE_AT_TIMESTEP_ZERO_PROB_START_ITER="${FREEZE_AT_TIMESTEP_ZERO_PROB_START_ITER}" \
  ENABLE_DEFAULT_POSE_PREPEND="${ENABLE_DEFAULT_POSE_PREPEND}" \
  DEFAULT_POSE_PREPEND_DURATION_S="${DEFAULT_POSE_PREPEND_DURATION_S}" \
  HOLOSOMA_RESET_TO_DEFAULT_POSE="${RESET_TO_DEFAULT_POSE}" \
  VISER_DISTILL_MINIMAL_UI="${VISER_DISTILL_MINIMAL_UI}" \
  VISER_SHOW_TARGET_KEYPOINTS="${VISER_SHOW_TARGET_KEYPOINTS}" \
  SCHEDULE_NAME="${SCHEDULE_NAME}" \
  SCHEDULE_NOTES="${SCHEDULE_NOTES}" \
  bash "${SCRIPT_DIR}/distill_box_perception.sh" "$@"
