#!/usr/bin/env bash
set -euo pipefail

# Hybrid drop-command perception training with a short online-BC warm start.
#
# This intentionally reuses distill_box_drop_mixed.sh for data selection,
# motion-bank preparation, perception settings, object geometry, and the current
# student actor observation:
#   ["actor_obs_proprio", "actor_obs_actions", "actor_obs_drop_command"] + perception_obs.
#
# Difference from distill_box_drop_mixed.sh:
# - 0..HYBRID_BC_ITERS: actor update is BC/DAgger on student-visited states
# - HYBRID_BC_ITERS..HYBRID_BC_END_ITER: BC weight ramps 1 -> 0 while PPO ramps 0 -> 1
# - 0..HYBRID_DENSE_ITERS: all environments remain on clip goals, so reward is
#   dense G1 + object tracking/reference guidance only
# - after HYBRID_DENSE_ITERS: command/external sparse-goal episodes ramp in

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

HYBRID_BC_ITERS=${HYBRID_BC_ITERS:-1000}
HYBRID_BC_RAMP_ITERS=${HYBRID_BC_RAMP_ITERS:-1000}
HYBRID_BC_END_ITER=${HYBRID_BC_END_ITER:-$((HYBRID_BC_ITERS + HYBRID_BC_RAMP_ITERS))}
HYBRID_DENSE_ITERS=${HYBRID_DENSE_ITERS:-5000}
NUM_LEARNING_ITERATIONS=${NUM_LEARNING_ITERATIONS:-20000}
HYBRID_SPARSE_END_ITER=${HYBRID_SPARSE_END_ITER:-${NUM_LEARNING_ITERATIONS}}
HYBRID_SPARSE_ENV_PROB_END=${HYBRID_SPARSE_ENV_PROB_END:-0.5}

DEFAULT_HYBRID_TEACHER_CHECKPOINT="${SCRIPT_DIR}/.teacher_checkpoints/model_17000.pt"
if [[ ! -f "${DEFAULT_HYBRID_TEACHER_CHECKPOINT}" ]]; then
  DEFAULT_HYBRID_TEACHER_CHECKPOINT="wandb://zihanw22/boxer/u5lguxvl/model_17000.pt"
fi
HYBRID_TEACHER_CHECKPOINT=${HYBRID_TEACHER_CHECKPOINT:-${TEACHER_CHECKPOINT:-${DEFAULT_HYBRID_TEACHER_CHECKPOINT}}}

EXP=${EXP:-g1-29dof-wbt-w-object-distill-sparse-goal-mixed-r2s-rollout-ref}
RUN_NAME=${RUN_NAME:-g1_w_object_hybrid_drop_mixed_r2s_rollout_ref}
TRAINING_NAME=${TRAINING_NAME:-g1_29dof_wbt_w_object_hybrid_drop_mixed_r2s_rollout_ref}
SCHEDULE_NAME=${SCHEDULE_NAME:-hybrid_drop_bc1k_ramp1k_dense_then_sparse}
SCHEDULE_NOTES=${SCHEDULE_NOTES:-"Hybrid drop-command training. Student observation matches distill_box_drop_mixed.sh. Iterations 0-${HYBRID_BC_ITERS} use online teacher-action BC on student-visited states; iterations ${HYBRID_BC_ITERS}-${HYBRID_BC_END_ITER} linearly ramp BC weight 1->0 and PPO weight 0->1. Iterations 0-${HYBRID_DENSE_ITERS} keep sparse command/external-goal probability at 0 so rewards are dense clip-goal G1/object tracking; sparse command/external-goal episodes ramp from ${HYBRID_DENSE_ITERS} to ${HYBRID_SPARSE_END_ITER}."}

STUDENT_ACTOR_INPUTS=${STUDENT_ACTOR_INPUTS:-"['actor_obs_proprio','actor_obs_actions','actor_obs_drop_command']"}
PERCEPTION_PRESET=${PERCEPTION_PRESET:-camera_depth_d435i}

SPARSE_GOAL_ENABLED=${SPARSE_GOAL_ENABLED:-True}
COMMAND_ONLY_ENV_PROB_START=${COMMAND_ONLY_ENV_PROB_START:-0.0}
COMMAND_ONLY_ENV_PROB_END=${COMMAND_ONLY_ENV_PROB_END:-${HYBRID_SPARSE_ENV_PROB_END}}
COMMAND_ONLY_ENV_PROB_START_ITER=${COMMAND_ONLY_ENV_PROB_START_ITER:-${HYBRID_DENSE_ITERS}}
COMMAND_ONLY_ENV_PROB_END_ITER=${COMMAND_ONLY_ENV_PROB_END_ITER:-${HYBRID_SPARSE_END_ITER}}
EXTERNAL_GOAL_PROB_START=${EXTERNAL_GOAL_PROB_START:-0.0}
EXTERNAL_GOAL_PROB_END=${EXTERNAL_GOAL_PROB_END:-${HYBRID_SPARSE_ENV_PROB_END}}
EXTERNAL_GOAL_PROB_START_ITER=${EXTERNAL_GOAL_PROB_START_ITER:-${HYBRID_DENSE_ITERS}}
EXTERNAL_GOAL_PROB_END_ITER=${EXTERNAL_GOAL_PROB_END_ITER:-${HYBRID_SPARSE_END_ITER}}
EXTERNAL_GOAL_RANGE_START_ITER=${EXTERNAL_GOAL_RANGE_START_ITER:-${HYBRID_DENSE_ITERS}}
EXTERNAL_GOAL_RANGE_END_ITER=${EXTERNAL_GOAL_RANGE_END_ITER:-${HYBRID_SPARSE_END_ITER}}

BC_LOSS_COEF=${BC_LOSS_COEF:-1.0}
DISTILL_ENABLED=${DISTILL_ENABLED:-True}
DAGGER_LOSS_COEF=${DAGGER_LOSS_COEF:-1.0}
PPO_START_EPOCH=${PPO_START_EPOCH:-${HYBRID_BC_ITERS}}
DAGGER_END_EPOCH=${DAGGER_END_EPOCH:-${HYBRID_BC_END_ITER}}
PPO_START_COEFF=${PPO_START_COEFF:-0.0}
PPO_TARGET_COEFF=${PPO_TARGET_COEFF:-1.0}
PPO_SCHEDULE_STEP_EPOCHS=${PPO_SCHEDULE_STEP_EPOCHS:-0}
PPO_START_NOISE_STD=${PPO_START_NOISE_STD:-}
SWITCH_TO_RL_AFTER=${SWITCH_TO_RL_AFTER:--1}
TEACHER_ACTION_MIX_RATIO=${TEACHER_ACTION_MIX_RATIO:-0.0}
TEACHER_PERCEPTION_PRESET=${TEACHER_PERCEPTION_PRESET:-none}
CRITIC_PERCEPTION_PRESET=${CRITIC_PERCEPTION_PRESET:-none}

echo "[INFO] hybrid_drop: online BC warm-start, then PPO"
echo "[INFO] exp=${EXP}"
echo "[INFO] teacher_checkpoint=${HYBRID_TEACHER_CHECKPOINT}"
echo "[INFO] student_actor_inputs=${STUDENT_ACTOR_INPUTS} perception=${PERCEPTION_PRESET}"
echo "[INFO] bc_until=${HYBRID_BC_ITERS} bc_ramp_end=${HYBRID_BC_END_ITER} ppo_coeff=${PPO_START_COEFF}->${PPO_TARGET_COEFF}"
echo "[INFO] dense_until=${HYBRID_DENSE_ITERS} sparse_ramp_end=${HYBRID_SPARSE_END_ITER} sparse_env_prob_end=${HYBRID_SPARSE_ENV_PROB_END}"

exec env \
  EXP="${EXP}" \
  RUN_NAME="${RUN_NAME}" \
  TRAINING_NAME="${TRAINING_NAME}" \
  NUM_LEARNING_ITERATIONS="${NUM_LEARNING_ITERATIONS}" \
  DEFAULT_TEACHER_CHECKPOINT="${HYBRID_TEACHER_CHECKPOINT}" \
  TEACHER_CHECKPOINT="${HYBRID_TEACHER_CHECKPOINT}" \
  SCHEDULE_NAME="${SCHEDULE_NAME}" \
  SCHEDULE_NOTES="${SCHEDULE_NOTES}" \
  STUDENT_ACTOR_INPUTS="${STUDENT_ACTOR_INPUTS}" \
  PERCEPTION_PRESET="${PERCEPTION_PRESET}" \
  SPARSE_GOAL_ENABLED="${SPARSE_GOAL_ENABLED}" \
  COMMAND_ONLY_ENV_PROB_START="${COMMAND_ONLY_ENV_PROB_START}" \
  COMMAND_ONLY_ENV_PROB_END="${COMMAND_ONLY_ENV_PROB_END}" \
  COMMAND_ONLY_ENV_PROB_START_ITER="${COMMAND_ONLY_ENV_PROB_START_ITER}" \
  COMMAND_ONLY_ENV_PROB_END_ITER="${COMMAND_ONLY_ENV_PROB_END_ITER}" \
  EXTERNAL_GOAL_PROB_START="${EXTERNAL_GOAL_PROB_START}" \
  EXTERNAL_GOAL_PROB_END="${EXTERNAL_GOAL_PROB_END}" \
  EXTERNAL_GOAL_PROB_START_ITER="${EXTERNAL_GOAL_PROB_START_ITER}" \
  EXTERNAL_GOAL_PROB_END_ITER="${EXTERNAL_GOAL_PROB_END_ITER}" \
  EXTERNAL_GOAL_RANGE_START_ITER="${EXTERNAL_GOAL_RANGE_START_ITER}" \
  EXTERNAL_GOAL_RANGE_END_ITER="${EXTERNAL_GOAL_RANGE_END_ITER}" \
  BC_LOSS_COEF="${BC_LOSS_COEF}" \
  DISTILL_ENABLED="${DISTILL_ENABLED}" \
  DAGGER_LOSS_COEF="${DAGGER_LOSS_COEF}" \
  PPO_START_EPOCH="${PPO_START_EPOCH}" \
  DAGGER_END_EPOCH="${DAGGER_END_EPOCH}" \
  PPO_START_COEFF="${PPO_START_COEFF}" \
  PPO_TARGET_COEFF="${PPO_TARGET_COEFF}" \
  PPO_SCHEDULE_STEP_EPOCHS="${PPO_SCHEDULE_STEP_EPOCHS}" \
  PPO_START_NOISE_STD="${PPO_START_NOISE_STD}" \
  SWITCH_TO_RL_AFTER="${SWITCH_TO_RL_AFTER}" \
  TEACHER_ACTION_MIX_RATIO="${TEACHER_ACTION_MIX_RATIO}" \
  TEACHER_PERCEPTION_PRESET="${TEACHER_PERCEPTION_PRESET}" \
  CRITIC_PERCEPTION_PRESET="${CRITIC_PERCEPTION_PRESET}" \
  bash "${SCRIPT_DIR}/distill_box_drop_mixed.sh" "$@"
