#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

if [[ $# -eq 0 ]]; then
  set -- box_75
fi

export COMMAND_WEB="${COMMAND_WEB:-0}"
export MJ_ENV_AUTO_LAUNCH_POLICY="${MJ_ENV_AUTO_LAUNCH_POLICY:-1}"
export POLICY_AUTO_START_MOTION_CLIP="${POLICY_AUTO_START_MOTION_CLIP:-1}"
export POLICY_STDIO="${POLICY_STDIO:-log}"
export HOLOSOMA_POLICY_TTY_INPUT="${HOLOSOMA_POLICY_TTY_INPUT:-0}"
export HOLOSOMA_POLICY_CONTROL_ALLOW_NONINTERACTIVE_AUTOSTART="${HOLOSOMA_POLICY_CONTROL_ALLOW_NONINTERACTIVE_AUTOSTART:-1}"
export SIM_MOTION_INIT_MODE="${SIM_MOTION_INIT_MODE:-raw_motion}"
export HOLOSOMA_MOTION_INIT_ZERO_VELOCITIES="${HOLOSOMA_MOTION_INIT_ZERO_VELOCITIES:-0}"
export AUTO_START_STIFF_HOLD_SEC="${AUTO_START_STIFF_HOLD_SEC:-0.0}"
export AUTO_START_STIFF_MAX_WAIT_SEC="${AUTO_START_STIFF_MAX_WAIT_SEC:-0.0}"
export AUTO_START_STIFF_POSE_TOL="${AUTO_START_STIFF_POSE_TOL:-0.12}"
export HOLOSOMA_KEYBOARD_ROOT_COMMAND="${HOLOSOMA_KEYBOARD_ROOT_COMMAND:-0}"
export HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST:-0}"
export HOLOSOMA_POLICY_TARGET_ROBOT_DOF_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_DOF_STATE_ASSIST:-0}"
export HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST:-0}"
export HOLOSOMA_MUJOCO_BACKSPACE_POLICY_CONTROL="${HOLOSOMA_MUJOCO_BACKSPACE_POLICY_CONTROL:-1}"
export HOLOSOMA_MUJOCO_BACKSPACE_AUTORESTART_POLICY="${HOLOSOMA_MUJOCO_BACKSPACE_AUTORESTART_POLICY:-1}"
export HOLOSOMA_MUJOCO_GUARD_DEFAULT_RESET="${HOLOSOMA_MUJOCO_GUARD_DEFAULT_RESET:-1}"

exec bash "$ROOT_DIR/mj_env.sh" "$@"
