#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

usage() {
  echo "Usage: bash mj_env.sh [box_75|motion.npz] [model.onnx|wandb-url]" >&2
}

is_truthy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

first_clip_arg() {
  local arg
  for arg in "$@"; do
    case "$arg" in
      depth|rendered|render|mujoco|rendered848|render848|mujoco848|warp|far_tracking_warp) ;;
      wandb://*|https://*|*.onnx|*.pt|--*) ;;
      *) printf '%s\n' "${arg%.npz}"; return 0 ;;
    esac
  done
  return 1
}

case "${1:-}" in
  -h|--help|help) usage; exit 0 ;;
esac

if [[ $# -eq 0 ]]; then
  set -- box_75
elif [[ "${1:-}" == wandb://* || "${1:-}" == https://* || "${1:-}" == *.onnx || "${1:-}" == *.pt ]]; then
  set -- box_75 "$@"
fi

export PYTHONSAFEPATH="${PYTHONSAFEPATH:-1}" PYTHONPATH="$ROOT_DIR/src/holosoma:$ROOT_DIR/src/holosoma_inference${PYTHONPATH:+:$PYTHONPATH}"
DEFAULT_MODEL_INPUT="${DEFAULT_MODEL_INPUT:-https://wandb.ai/zihanw22/boxer/runs/w5qostjn}"
export DEFAULT_MODEL_INPUT MODEL_INPUT="${MODEL_INPUT:-${MODEL_PATH:-${MODEL_REF:-$DEFAULT_MODEL_INPUT}}}"
export PERCEPTION_CAMERA_SOURCE="${PERCEPTION_CAMERA_SOURCE:-far_tracking_warp}" PERCEPTION_OBJECT_GEOMETRY_MODE="${PERCEPTION_OBJECT_GEOMETRY_MODE:-mesh}" HOLOSOMA_STRICT_PERCEPTION_CAMERA_SOURCE="${HOLOSOMA_STRICT_PERCEPTION_CAMERA_SOURCE:-1}"

export SIM_CLOCK_PORT="${SIM_CLOCK_PORT:-5655}" SIM_STATE_PORT="${SIM_STATE_PORT:-5657}" PERCEPTION_OBS_PORT="${PERCEPTION_OBS_PORT:-5658}" SIM_CONTROL_PORT="${SIM_CONTROL_PORT:-5659}"
export SPARSE_ROOT_COMMAND_PORT="${SPARSE_ROOT_COMMAND_PORT:-5661}" POLICY_CONTROL_PORT="${POLICY_CONTROL_PORT:-5662}" POLICY_OVERLAY_PORT="${POLICY_OVERLAY_PORT:-5663}" HOLOSOMA_POLICY_OVERLAY_PORT="${HOLOSOMA_POLICY_OVERLAY_PORT:-${POLICY_OVERLAY_PORT:-5663}}"
PERCEPTION_OBS_SHM_NAME="${PERCEPTION_OBS_SHM_NAME:-depth_img_shm_${SIM_STATE_PORT}}"
export PERCEPTION_OBS_SHM_NAME HOLOSOMA_POLICY_PERCEPTION_OBS_SHM_NAME="${HOLOSOMA_POLICY_PERCEPTION_OBS_SHM_NAME:-policy_${PERCEPTION_OBS_SHM_NAME}}"

export HOLOSOMA_MJ_TRACK_INTERNAL_CORE=1 MJ_TRACK_MODE=both SKIP_POLICY=0 ENABLE_EXTERNAL_SPARSE_ROOT_COMMAND="${ENABLE_EXTERNAL_SPARSE_ROOT_COMMAND:-1}" HOLOSOMA_MUJOCO_MANUAL_SPARSE_ROOT_COMMAND="${HOLOSOMA_MUJOCO_MANUAL_SPARSE_ROOT_COMMAND:-1}" PERCEPTION_OBS_TRANSPORT="${PERCEPTION_OBS_TRANSPORT:-shm}" POLICY_USE_PERCEPTION_OBS_SHM="${POLICY_USE_PERCEPTION_OBS_SHM:-1}" RUN_SECONDS="${RUN_SECONDS:-0}" HOLOSOMA_MJ_TRACK_RUN_FOREVER="${HOLOSOMA_MJ_TRACK_RUN_FOREVER:-1}"
export POLICY_STDIO="${POLICY_STDIO:-inherit}" HOLOSOMA_FORCE_MANUAL_SPARSE_ROOT_COMMAND="${HOLOSOMA_FORCE_MANUAL_SPARSE_ROOT_COMMAND:-1}" HOLOSOMA_KEYBOARD_ROOT_COMMAND="${HOLOSOMA_KEYBOARD_ROOT_COMMAND:-1}" HOLOSOMA_KEYBOARD_ROOT_COMMAND_MODE="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_MODE:-manual}" HOLOSOMA_KEYBOARD_ROOT_COMMAND_INPUT_MODE="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_INPUT_MODE:-latch}" HOLOSOMA_KEYBOARD_ROOT_COMMAND_VALUE="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_VALUE:-0.1}" HOLOSOMA_KEYBOARD_ROOT_COMMAND_YAW_DEGREES="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_YAW_DEGREES:-17}"

export SIM_MOTION_INIT_MODE="${SIM_MOTION_INIT_MODE:-raw_motion}" HOLOSOMA_MUJOCO_BACKSPACE_POLICY_CONTROL="${HOLOSOMA_MUJOCO_BACKSPACE_POLICY_CONTROL:-1}" HOLOSOMA_MUJOCO_BACKSPACE_AUTORESTART_POLICY="${HOLOSOMA_MUJOCO_BACKSPACE_AUTORESTART_POLICY:-1}" HOLOSOMA_MUJOCO_GUARD_DEFAULT_RESET="${HOLOSOMA_MUJOCO_GUARD_DEFAULT_RESET:-1}"
export HOLOSOMA_DISABLE_AUTO_RESET="${HOLOSOMA_DISABLE_AUTO_RESET:-1}" HOLOSOMA_DISABLE_MOTION_END_RESET="${HOLOSOMA_DISABLE_MOTION_END_RESET:-1}" HOLOSOMA_DISABLE_CLIP_END_RESET="${HOLOSOMA_DISABLE_CLIP_END_RESET:-1}" HOLOSOMA_DISABLE_BAD_TRACKING_RESET="${HOLOSOMA_DISABLE_BAD_TRACKING_RESET:-1}"

export GT_MUJOCO_PHYSICS="${GT_MUJOCO_PHYSICS:-1}" HOLOSOMA_GT_MUJOCO_PHYSICS="${HOLOSOMA_GT_MUJOCO_PHYSICS:-${GT_MUJOCO_PHYSICS:-1}}" MUJOCO_OBJECT_MASS_OVERRIDE="${MUJOCO_OBJECT_MASS_OVERRIDE:-1.4}"
export MUJOCO_OBJECT_GEOM_FRICTION="${MUJOCO_OBJECT_GEOM_FRICTION:-[0.6,0.02,0.005]}" MUJOCO_OBJECT_TERRAIN_PAIR_FRICTION="${MUJOCO_OBJECT_TERRAIN_PAIR_FRICTION:-[0.6,0.02,0.005]}"
export HOLOSOMA_MOTION_INIT_ZERO_VELOCITIES="${HOLOSOMA_MOTION_INIT_ZERO_VELOCITIES:-0}" HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST:-0}" HOLOSOMA_POLICY_TARGET_ROBOT_DOF_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_DOF_STATE_ASSIST:-0}" HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST:-0}"

export PERCEPTION_CAMERA_WIDTH="${PERCEPTION_CAMERA_WIDTH:-106}" PERCEPTION_CAMERA_HEIGHT="${PERCEPTION_CAMERA_HEIGHT:-60}" PERCEPTION_CAMERA_NEAR="${PERCEPTION_CAMERA_NEAR:-0.3}" PERCEPTION_CAMERA_FAR="${PERCEPTION_CAMERA_FAR:-3.0}" PERCEPTION_MAX_DISTANCE="${PERCEPTION_MAX_DISTANCE:-3.0}"
export PERCEPTION_CAMERA_WARP_CROP_TOP="${PERCEPTION_CAMERA_WARP_CROP_TOP:-2}" PERCEPTION_CAMERA_WARP_CROP_BOTTOM="${PERCEPTION_CAMERA_WARP_CROP_BOTTOM:-0}" PERCEPTION_CAMERA_WARP_CROP_LEFT="${PERCEPTION_CAMERA_WARP_CROP_LEFT:-4}" PERCEPTION_CAMERA_WARP_CROP_RIGHT="${PERCEPTION_CAMERA_WARP_CROP_RIGHT:-4}" PERCEPTION_CAMERA_WARP_MIN_VALID_DEPTH="${PERCEPTION_CAMERA_WARP_MIN_VALID_DEPTH:-0.15}"

export TRAINING_HEADLESS="${TRAINING_HEADLESS:-${HEADLESS:-False}}"

clip="$(first_clip_arg "$@" || true)"
if [[ -z "${MOTION_DIR:-}" && -n "$clip" && -f "$ROOT_DIR/data_demo/${clip}.npz" ]]; then
  export MOTION_DIR="$ROOT_DIR/data_demo"
  export OBJECT_URDF="${OBJECT_URDF:-$ROOT_DIR/data_demo/_clip_object_urdf_map.json}"
fi

if is_truthy "${MJ_ENV_VERBOSE:-0}"; then
  exec bash "$ROOT_DIR/mj_box_depth_track.sh" "$@"
fi

log="${MJ_ENV_LAUNCH_LOG:-$ROOT_DIR/logs/live_debug/mj_env_launch.log}"
mkdir -p "$(dirname "$log")"
set +e
bash "$ROOT_DIR/mj_box_depth_track.sh" "$@" >"$log" 2>&1
status=$?
set -e
if [[ "$status" -ne 0 ]]; then
  tail -n 80 "$log" >&2 || true
fi
exit "$status"
