#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
CLIP="${1:-box_75}"; CLIP="${CLIP%.npz}"
MOTION="data_demo/${CLIP}.npz"; MODEL="${2:-logs/wandb_runs/shoo7sr1/model_29999.onnx}"; PATCH_DIR="${PATCH_DIR:-logs/live_debug/mj_rollout}"; PATCHED="${PATCH_DIR}/$(basename "${MODEL%.onnx}")__${CLIP}.onnx"
OFFSET="${HOLOSOMA_POLICY_MOTION_INDEX_OFFSET:-0}"; [[ "$CLIP" == "box_75" ]] && OFFSET="${HOLOSOMA_POLICY_MOTION_INDEX_OFFSET:-5}"
mkdir -p "$PATCH_DIR"; [[ -f "$MOTION" ]] || { echo "missing data_demo motion: $MOTION" >&2; exit 1; }
MODEL="$(python scripts/mj_resolve_wandb_model.py "$MODEL")"
PYTHONSAFEPATH=1 PYTHONPATH="src/holosoma_inference${PYTHONPATH:+:$PYTHONPATH}" python src/holosoma_inference/holosoma_inference/tools/patch_motion_onnx.py --model-path "$MODEL" --motion-file "$MOTION" --output-path "$PATCHED" >/dev/null
PYTHONSAFEPATH=1 PYTHONPATH="src/holosoma_inference${PYTHONPATH:+:$PYTHONPATH}" HOLOSOMA_POLICY_TTY_INPUT="${HOLOSOMA_POLICY_TTY_INPUT:-1}" HOLOSOMA_KEYBOARD_ROOT_COMMAND="${HOLOSOMA_KEYBOARD_ROOT_COMMAND:-1}" HOLOSOMA_KEYBOARD_ROOT_COMMAND_VALUE="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_VALUE:-0.5}" HOLOSOMA_KEYBOARD_ROOT_COMMAND_YAW_DEGREES="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_YAW_DEGREES:-17}" HOLOSOMA_SKIP_STIFF_PROMPT="${HOLOSOMA_SKIP_STIFF_PROMPT:-1}" HOLOSOMA_DISABLE_AUTO_RESET="${HOLOSOMA_DISABLE_AUTO_RESET:-1}" HOLOSOMA_DISABLE_MOTION_END_RESET="${HOLOSOMA_DISABLE_MOTION_END_RESET:-1}" HOLOSOMA_DISABLE_CLIP_END_RESET="${HOLOSOMA_DISABLE_CLIP_END_RESET:-1}" HOLOSOMA_DISABLE_BAD_TRACKING_RESET="${HOLOSOMA_DISABLE_BAD_TRACKING_RESET:-1}" HOLOSOMA_POLICY_MOTION_INDEX_OFFSET="$OFFSET" python -u src/holosoma_inference/holosoma_inference/run_policy.py inference:g1-29dof-wbt-object-distill --task.model-path "$PATCHED" --task.motion-file "$MOTION" --task.interface lo --task.use-sim-state --task.sim-clock-port 5655 --task.sim-state-port 5657 --task.sim-control-port 5659 --task.no-auto-start-motion --task.auto-start-stiff-hold-sec 0.0 --task.auto-start-stiff-max-wait-sec 0.0 --task.policy-action-scale 1.0 --task.rl-rate 50 --task.sim-object-name object --task.use-zmq-lowcmd --task.use-split-perception-obs --task.perception-obs-port 5658 --task.use-split-perception-obs-shm --task.perception-obs-shm-name depth_img_shm_5657 --task.use-external-sparse-root-command --task.sparse-root-command-port 5661 --task.use-sim-time --task.prefer-sim-ref-from-sim-state --task.defer-policy-start-until-valid-state
