#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_MODEL_REF="${DEFAULT_MODEL_REF:-wandb://zihanw22/boxer/u5lguxvl/latest.onnx}"
DEFAULT_MOTION_DIR="${DEFAULT_MOTION_DIR:-${ROOT_DIR}/outputs/motion_bank_success_box_0_92_0p3}"
DEFAULT_CLIP_NAME="${DEFAULT_CLIP_NAME:-box_74}"

usage() {
  cat <<EOF
Usage:
  bash mj_track_generalist_success.sh [clip_name|motion.npz] [model.onnx|wandb://...] [mj_track args...]

Purpose:
  Run the object-generalist MuJoCo tracker on the success-rollout motion bank.

Defaults:
  model      = ${DEFAULT_MODEL_REF}
  motion dir = ${DEFAULT_MOTION_DIR}
  clip       = ${DEFAULT_CLIP_NAME}

Examples:
  bash mj_track_generalist_success.sh
  bash mj_track_generalist_success.sh box_74
  bash mj_track_generalist_success.sh --motion-dir /abs/path/to/success_bank
EOF
}

case "${1:-}" in
  -h|--help|help)
    usage
    exit 0
    ;;
esac

export DEFAULT_MODEL_REF
export DEFAULT_MOTION_DIR
export DEFAULT_CLIP_NAME
export SIM_CLOCK_PORT="${SIM_CLOCK_PORT:-6655}"
export SIM_STATE_PORT="${SIM_STATE_PORT:-6657}"
export PERCEPTION_OBS_PORT="${PERCEPTION_OBS_PORT:-6658}"
export SIM_CONTROL_PORT="${SIM_CONTROL_PORT:-6659}"
export SPARSE_ROOT_COMMAND_PORT="${SPARSE_ROOT_COMMAND_PORT:-6661}"
export POLICY_CONTROL_PORT="${POLICY_CONTROL_PORT:-6662}"
export POLICY_OVERLAY_PORT="${POLICY_OVERLAY_PORT:-6663}"
export HOLOSOMA_POLICY_OVERLAY_PORT="${HOLOSOMA_POLICY_OVERLAY_PORT:-${POLICY_OVERLAY_PORT}}"
export HOLOSOMA_SKIP_STIFF_PROMPT="${HOLOSOMA_SKIP_STIFF_PROMPT:-1}"
export HOLOSOMA_W_OBJECT_URDF="${HOLOSOMA_W_OBJECT_URDF:-g1/g1_29dof.urdf}"
export SIM_SUBSTEPS="${SIM_SUBSTEPS:-4}"
export SIM_COPY_JOINT_DEFAULTS_FROM_ROBOT_XML="${SIM_COPY_JOINT_DEFAULTS_FROM_ROBOT_XML:-}"
export SIM_COPY_TENDONS_FROM_ROBOT_XML="${SIM_COPY_TENDONS_FROM_ROBOT_XML:-}"
export SIM_COPY_COLLISION_GEOMS_FROM_ROBOT_XML="${SIM_COPY_COLLISION_GEOMS_FROM_ROBOT_XML:-}"
export SIM_COPY_CONTACT_PAIRS_FROM_ROBOT_XML="${SIM_COPY_CONTACT_PAIRS_FROM_ROBOT_XML:-}"
export MUJOCO_LIMIT_OBJECT_CONTACTS_TO_CARRY_BODIES="${MUJOCO_LIMIT_OBJECT_CONTACTS_TO_CARRY_BODIES:-}"
export MUJOCO_OBJECT_CONTACT_BODY_MARKERS="${MUJOCO_OBJECT_CONTACT_BODY_MARKERS:-}"
export USE_TRAINING_OBJECT_CONTACT_MARKERS="${USE_TRAINING_OBJECT_CONTACT_MARKERS:-1}"
export HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST:-0}"
export HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST:-0}"
export HOLOSOMA_ZMQ_LOWCMD_KP_SCALE="${HOLOSOMA_ZMQ_LOWCMD_KP_SCALE:-0.8}"
export HOLOSOMA_ZMQ_LOWCMD_KD_SCALE="${HOLOSOMA_ZMQ_LOWCMD_KD_SCALE:-1.0}"
export HOLOSOMA_ZMQ_LOWCMD_TORQUE_LIMIT_SCALE="${HOLOSOMA_ZMQ_LOWCMD_TORQUE_LIMIT_SCALE:-1.0}"
export HOLOSOMA_ONNX_ACTION_SCALE_OVERRIDE="${HOLOSOMA_ONNX_ACTION_SCALE_OVERRIDE:-1.0}"

exec bash "${ROOT_DIR}/mj_track_generalist.sh" "$@"
