#!/usr/bin/env bash
set -euo pipefail

# Prepare BEHAVE sq-object training bank from retarget outputs.
#
# Source (retarget raw):
#   src/holosoma_retargeting/demo_results_parallel/g1/object_interaction/behave_zup_sq_obj/*.npz
#
# Output (training-ready):
#   src/holosoma_retargeting/converted_res/behave_sq_obj/*_mj_w_obj.npz
#   src/holosoma_retargeting/converted_res/behave_sq_obj/_clip_object_urdf_map.json
#
# Optional env:
#   RAW_DIR=/abs/path/to/raw_npz_dir
#   CONVERTED_DIR=/abs/path/to/output_npz_dir
#   RUN_CONVERT=1|0
#   CLEAN_CONVERTED=1|0
#   PYTHON_BIN=python

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
RAW_DIR=${RAW_DIR:-"${SCRIPT_DIR}/src/holosoma_retargeting/demo_results_parallel/g1/object_interaction/behave_zup_sq_obj"}
CONVERTED_DIR=${CONVERTED_DIR:-"${SCRIPT_DIR}/src/holosoma_retargeting/converted_res/behave_sq_obj"}
RUN_CONVERT=${RUN_CONVERT:-1}
CLEAN_CONVERTED=${CLEAN_CONVERTED:-1}
PYTHON_BIN=${PYTHON_BIN:-python}

if [[ ! -d "${RAW_DIR}" ]]; then
  echo "[ERROR] RAW_DIR not found: ${RAW_DIR}" >&2
  exit 1
fi

if [[ "${CLEAN_CONVERTED}" == "1" ]]; then
  rm -rf "${CONVERTED_DIR}"
fi
mkdir -p "${CONVERTED_DIR}"

if [[ "${RUN_CONVERT}" == "1" ]]; then
  echo "[INFO] Converting raw retarget npz -> training npz ..."
  INPUT_DIR="${RAW_DIR}" OUTPUT_DIR="${CONVERTED_DIR}" DATA_FORMAT="behave_zup" PYTHON_BIN="${PYTHON_BIN}" \
    bash "${SCRIPT_DIR}/retgt_post_behave.sh"
fi

MAP_FILE="${CONVERTED_DIR}/_clip_object_urdf_map.json"
"${PYTHON_BIN}" - "${RAW_DIR}" "${CONVERTED_DIR}" "${MAP_FILE}" <<'PY'
import json
import sys
from pathlib import Path

import numpy as np

raw_dir = Path(sys.argv[1])
converted_dir = Path(sys.argv[2])
map_file = Path(sys.argv[3])

raw_files = sorted(raw_dir.glob("*.npz"))
if not raw_files:
    raise SystemExit(f"[ERROR] No raw npz found in {raw_dir}")

converted_files = sorted(converted_dir.glob("*_mj_w_obj.npz"))
if not converted_files:
    raise SystemExit(f"[ERROR] No converted *_mj_w_obj.npz found in {converted_dir}")

def scalar_str(v) -> str:
    arr = np.asarray(v)
    if arr.size == 0:
        return ""
    if arr.shape == ():
        item = arr.item()
    else:
        item = arr.reshape(-1)[0]
        if hasattr(item, "item"):
            item = item.item()
    return str(item).strip()

raw_map: dict[str, dict[str, str]] = {}
for p in raw_files:
    clip = p.stem
    if clip.endswith("_original"):
        clip = clip[:-9]
    with np.load(p, allow_pickle=True) as d:
        object_name = scalar_str(d["object_name"]) if "object_name" in d else ""
        object_urdf_path = scalar_str(d["object_urdf_path"]) if "object_urdf_path" in d else ""
    raw_map[clip] = {
        "object_name": object_name,
        "object_urdf_path": object_urdf_path,
    }

clip_map: dict[str, dict[str, str]] = {}
missing: list[str] = []
for p in converted_files:
    stem = p.stem
    clip = stem[:-9] if stem.endswith("_mj_w_obj") else stem
    entry = {"object_name": "", "object_urdf_path": ""}

    with np.load(p, allow_pickle=True) as d:
        if "object_name" in d:
            entry["object_name"] = scalar_str(d["object_name"])
        if "object_urdf_path" in d:
            entry["object_urdf_path"] = scalar_str(d["object_urdf_path"])

    raw_entry = raw_map.get(clip, {})
    if not entry["object_name"]:
        entry["object_name"] = raw_entry.get("object_name", "")
    if not entry["object_urdf_path"]:
        entry["object_urdf_path"] = raw_entry.get("object_urdf_path", "")

    if not entry["object_name"] and entry["object_urdf_path"]:
        entry["object_name"] = Path(entry["object_urdf_path"]).stem

    if not entry["object_urdf_path"]:
        missing.append(clip)
        continue

    urdf_path = Path(entry["object_urdf_path"])
    if not urdf_path.is_absolute():
        urdf_path = (converted_dir / urdf_path).resolve()
        entry["object_urdf_path"] = str(urdf_path)

    if not urdf_path.exists():
        raise SystemExit(f"[ERROR] URDF missing for clip '{clip}': {urdf_path}")

    clip_map[stem] = entry

if missing:
    raise SystemExit(f"[ERROR] Missing object_urdf_path for clips: {missing[:10]}")

payload = {
    "clips": clip_map,
    "notes": "Generated by prepare_behave_sq_training_bank.sh",
    "source_raw_dir": str(raw_dir.resolve()),
    "source_converted_dir": str(converted_dir.resolve()),
}
map_file.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

unique_objects = sorted({v["object_name"] for v in clip_map.values()})
print(f"[INFO] Wrote {map_file} with {len(clip_map)} clips")
print(f"[INFO] Objects: {unique_objects}")
PY

echo "[INFO] Done."
echo "[INFO] Training motion dir: ${CONVERTED_DIR}"
echo "[INFO] Clip->URDF map     : ${MAP_FILE}"
