#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export NPROC=${NPROC:-4}
export PER_GPU_ENVS=${PER_GPU_ENVS:-8192}
export NUM_ENVS=${NUM_ENVS:-$((NPROC * PER_GPU_ENVS))}
export PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY=${PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY:-33554432}

echo "[INFO] MINI launcher: NPROC=${NPROC} PER_GPU_ENVS=${PER_GPU_ENVS} NUM_ENVS=${NUM_ENVS} PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY=${PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY}"

exec bash "${SCRIPT_DIR}/train_object_generalist_ds.sh" "$@"
