#!/usr/bin/env bash
set -euo pipefail

# AS generalist training on the CoRL real-data union bank.
# All training data is read from repo-local data/. Run cp_baseline.sh first.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
cd "${REPO_ROOT}"

LOCAL_DATA_ROOT="${REPO_ROOT}/data"
REALDATA_ROOT=${REALDATA_ROOT:-data/corl_numbers}
OMOMO_REALDATA_DIR=${OMOMO_REALDATA_DIR:-"${REALDATA_ROOT}/omomo_z0p4_nofoot_bimanual161_training_ready"}
BEHAVE_REALDATA_DIR=${BEHAVE_REALDATA_DIR:-"${REALDATA_ROOT}/behave_z0p4_first_lift_run_bimanual56_w_obj_training_ready"}
REALDATA_UNION_DIR=${REALDATA_UNION_DIR:-"${REALDATA_ROOT}/realdata_union"}
REALDATA_CONTACT_EXPORT_ROOT=${REALDATA_CONTACT_EXPORT_ROOT:-"${REALDATA_UNION_DIR}/contact_export_from_retarget"}

python3 - "${LOCAL_DATA_ROOT}" "${OMOMO_REALDATA_DIR}" "${BEHAVE_REALDATA_DIR}" "${REALDATA_UNION_DIR}" <<'PY'
import json
import os
import shutil
import sys
from pathlib import Path

local_data_root = Path(sys.argv[1]).expanduser().resolve()
source_dirs = [Path(raw).expanduser().resolve() for raw in sys.argv[2:4]]
out_dir = Path(sys.argv[4]).expanduser().resolve()
marker = out_dir / ".generated_by_train_as_general_realdata"

def require_under_data(path: Path, label: str) -> None:
    if path != local_data_root and local_data_root not in path.parents:
        raise SystemExit(
            f"[ERROR] {label} must be under repo-local data/: {path}\n"
            "[ERROR] Run ./cp_baseline.sh first; training must not read /nfs directly."
        )


for source_dir in source_dirs:
    require_under_data(source_dir, "realdata source dir")
require_under_data(out_dir, "realdata union dir")

for source_dir in source_dirs:
    if not source_dir.is_dir():
        raise SystemExit(f"[ERROR] Missing realdata source dir: {source_dir}. Run ./cp_baseline.sh first.")
    if not (source_dir / "_clip_object_urdf_map.json").is_file():
        raise SystemExit(f"[ERROR] Missing object map: {source_dir / '_clip_object_urdf_map.json'}")
    if not any(source_dir.glob("*.npz")):
        raise SystemExit(f"[ERROR] No .npz clips found in: {source_dir}")

if out_dir.exists():
    if not marker.exists():
        raise SystemExit(
            f"[ERROR] Refusing to clean non-generated union dir: {out_dir}. "
            "Set REALDATA_UNION_DIR to an empty/generated path."
        )
    for child in out_dir.iterdir():
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()
else:
    out_dir.mkdir(parents=True)


def load_clips(map_path: Path) -> dict:
    payload = json.loads(map_path.read_text(encoding="utf-8"))
    clips = payload.get("clips", payload) if isinstance(payload, dict) else {}
    if not isinstance(clips, dict) or not clips:
        raise SystemExit(f"[ERROR] Invalid object map: {map_path}")
    return clips


def local_relative_entry(entry: dict, map_dir: Path, relative_to: Path) -> dict:
    out = dict(entry)
    for key in ("object_urdf_path", "object_mesh_path"):
        raw = str(out.get(key, "")).strip()
        if not raw:
            continue
        path = Path(raw).expanduser()
        if not path.is_absolute():
            path = map_dir / path
        path = path.resolve()
        require_under_data(path, f"{key} asset")
        out[key] = os.path.relpath(path, relative_to)
    return out


merged_clips = {}
source_summary = {}
for source_dir in source_dirs:
    clips = load_clips(source_dir / "_clip_object_urdf_map.json")
    npz_files = sorted(source_dir.glob("*.npz"))
    source_summary[source_dir.name] = len(npz_files)
    for npz_path in npz_files:
        clip_id = npz_path.stem
        if clip_id in merged_clips:
            raise SystemExit(f"[ERROR] Duplicate clip id across realdata sources: {clip_id}")
        if clip_id not in clips:
            raise SystemExit(f"[ERROR] Missing object-map entry for {clip_id} in {source_dir}")
        (out_dir / npz_path.name).symlink_to(os.path.relpath(npz_path, out_dir))
        merged_clips[clip_id] = local_relative_entry(clips[clip_id], source_dir, out_dir)

payload = {
    "clips": merged_clips,
    "source_dirs": [str(path) for path in source_dirs],
    "source_counts": source_summary,
    "notes": "Generated symlink union for corl_numbers/train_as_general_realdata.sh.",
}
(out_dir / "_clip_object_urdf_map.json").write_text(
    json.dumps(payload, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)
marker.write_text("generated by corl_numbers/train_as_general_realdata.sh\n", encoding="utf-8")
print(f"[INFO] Prepared CoRL realdata union: {out_dir} ({len(merged_clips)} clips)")
PY

python3 - "${LOCAL_DATA_ROOT}" "${REALDATA_CONTACT_EXPORT_ROOT}" <<'PY'
import sys
from pathlib import Path

local_data_root = Path(sys.argv[1]).expanduser().resolve()
contact_root = Path(sys.argv[2]).expanduser().resolve()
if contact_root != local_data_root and local_data_root not in contact_root.parents:
    raise SystemExit(
        f"[ERROR] REALDATA_CONTACT_EXPORT_ROOT must be under repo-local data/: {contact_root}"
    )
PY
mkdir -p "${REALDATA_CONTACT_EXPORT_ROOT}"

export AS_DATA_DIR="${REALDATA_UNION_DIR}"
export AS_OBJECT_MAP="${REALDATA_UNION_DIR}/_clip_object_urdf_map.json"
export AS_EXPECTED_TOTAL=${AS_EXPECTED_TOTAL:-217}
export CONTACT_EXPORT_ROOT="${REALDATA_CONTACT_EXPORT_ROOT}"
export SEQUENCE_NAME=${SEQUENCE_NAME:-as-general-realdata-corl}

exec bash "${REPO_ROOT}/train_as_general.sh" "$@"
