#!/usr/bin/env bash
set -euo pipefail

# AS generalist training on the CoRL real-data union bank.
# All training data is read from repo-local data/. Run cp_baseline.sh first.
#
# The public union path is an atomic symlink to a read-only, content-addressed
# generation.  A generation is built completely in a sibling staging
# directory before it can become visible to training.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
cd "${REPO_ROOT}"

LOCAL_DATA_ROOT="${REPO_ROOT}/data"
REALDATA_ROOT=${REALDATA_ROOT:-data/corl_numbers}
OMOMO_REALDATA_DIR=${OMOMO_REALDATA_DIR:-"${REALDATA_ROOT}/omomo_z0p4_nofoot_bimanual161_training_ready"}
BEHAVE_REALDATA_DIR=${BEHAVE_REALDATA_DIR:-"${REALDATA_ROOT}/behave_z0p4_first_lift_run_bimanual56_w_obj_training_ready"}
REALDATA_UNION_DIR=${REALDATA_UNION_DIR:-"${REALDATA_ROOT}/realdata_union"}
# Contact exports are mutable experiment output.  They must not live below the
# immutable union alias/generation.
REALDATA_CONTACT_EXPORT_ROOT=${REALDATA_CONTACT_EXPORT_ROOT:-"${REALDATA_ROOT}/realdata_contact_export_from_retarget"}
# train_as_general.sh builds a second, content-addressed single-slot view.  Its
# writable base must also stay outside the immutable union generation.
AS_SINGLE_SLOT_MOTION_BASE=${AS_SINGLE_SLOT_MOTION_BASE:-${AS_SINGLE_SLOT_MOTION_DIR:-"${REALDATA_ROOT}/realdata_union_single_slot_motion_bank"}}
AS_EXPECTED_TOTAL=${AS_EXPECTED_TOTAL:-217}
# These CoRL banks do not ship contact sidecars.  The scientifically runnable
# default is therefore the contact-free generalist reward.  Users may opt into
# offline contact guidance only after supplying a complete contact export.
REWARD_CONFIG=${REWARD_CONFIG:-g1-29dof-wbt-w-object-generalist}

python3 - \
  "${REPO_ROOT}" \
  "${LOCAL_DATA_ROOT}" \
  "${OMOMO_REALDATA_DIR}" \
  "${BEHAVE_REALDATA_DIR}" \
  "${REALDATA_UNION_DIR}" \
  "${REALDATA_CONTACT_EXPORT_ROOT}" \
  "${AS_SINGLE_SLOT_MOTION_BASE}" \
  "${AS_EXPECTED_TOTAL}" <<'PY'
from __future__ import annotations

import ctypes
import fcntl
import hashlib
import json
import os
import shutil
import stat
import sys
import uuid
from pathlib import Path
from typing import Any, NoReturn


GENERATOR = "corl_numbers/train_as_general_realdata.sh"
GENERATION_SCHEMA_VERSION = 2
MARKER_NAME = ".generated_by_train_as_general_realdata"
MANIFEST_NAME = "realdata_union_manifest.json"
LEGACY_MARKER_TEXT = f"generated by {GENERATOR}\n"
CHUNK_SIZE = 8 * 1024 * 1024


def fail(message: str) -> NoReturn:
    raise SystemExit(f"[ERROR] {message}")


def lexical_path(raw: str | Path) -> Path:
    return Path(os.path.abspath(os.path.expanduser(str(raw))))


def is_within(path: Path, root: Path, *, strict: bool = False) -> bool:
    if path == root:
        return not strict
    return root in path.parents


def require_owned_path(path: Path, root: Path, label: str, *, strict: bool = False) -> None:
    if not is_within(path, root, strict=strict):
        relation = "strictly under" if strict else "under"
        fail(
            f"{label} must be {relation} repo-local data/: {path}. "
            "Aliases to /nfs or any other external root are forbidden."
        )


def reject_symlink_components(
    path: Path,
    root: Path,
    label: str,
    *,
    include_leaf: bool,
) -> None:
    """Reject path aliases before resolving them.

    This is intentionally stricter than merely checking the final resolved
    path.  It prevents an in-repo component from being swapped into an alias
    that redirects a later write outside the owned data root.
    """

    require_owned_path(path, root, label)
    if root.is_symlink():
        fail(f"repo-local data root must not be a symlink: {root}")
    relative = path.relative_to(root)
    parts = relative.parts if include_leaf else relative.parts[:-1]
    current = root
    for part in parts:
        current = current / part
        if current.is_symlink():
            fail(f"{label} contains a forbidden symlink component: {current}")


def paths_overlap(left: Path, right: Path) -> bool:
    return left == right or left in right.parents or right in left.parents


def canonical_json_bytes(payload: Any) -> bytes:
    try:
        return json.dumps(
            payload,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        fail(f"metadata is not canonical JSON: {exc}")


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def stable_file_digest(path: Path, data_root: Path, label: str) -> dict[str, Any]:
    reject_symlink_components(path, data_root, label, include_leaf=True)
    try:
        before = path.stat()
    except FileNotFoundError:
        fail(f"missing {label}: {path}")
    if not stat.S_ISREG(before.st_mode):
        fail(f"{label} must be a regular file: {path}")

    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            while chunk := handle.read(CHUNK_SIZE):
                digest.update(chunk)
    except OSError as exc:
        fail(f"could not read {label} {path}: {exc}")
    after = path.stat()
    signature = (
        before.st_dev,
        before.st_ino,
        before.st_size,
        before.st_mtime_ns,
        before.st_ctime_ns,
    )
    if signature != (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
        after.st_ctime_ns,
    ):
        fail(f"{label} changed while its content digest was computed: {path}")
    return {
        "path": path.relative_to(data_root).as_posix(),
        "size": before.st_size,
        "sha256": digest.hexdigest(),
        "_signature": signature,
    }


def stable_read_bytes(path: Path, data_root: Path, label: str) -> tuple[bytes, dict[str, Any]]:
    record = stable_file_digest(path, data_root, label)
    payload = path.read_bytes()
    if len(payload) != record["size"] or sha256_bytes(payload) != record["sha256"]:
        fail(f"{label} changed between validation reads: {path}")
    return payload, record


def public_record(record: dict[str, Any]) -> dict[str, Any]:
    return {key: record[key] for key in ("path", "size", "sha256")}


def validate_source_file_unchanged(path: Path, record: dict[str, Any], label: str) -> None:
    current = path.stat()
    current_signature = (
        current.st_dev,
        current.st_ino,
        current.st_size,
        current.st_mtime_ns,
        current.st_ctime_ns,
    )
    if current_signature != record["_signature"]:
        fail(f"{label} changed after its content digest was computed: {path}")


def copy_verified(
    source: Path,
    destination: Path,
    record: dict[str, Any],
    data_root: Path,
    label: str,
) -> None:
    reject_symlink_components(source, data_root, label, include_leaf=True)
    validate_source_file_unchanged(source, record, label)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination, follow_symlinks=False)
    # The destination is below a private staging root rather than data_root, so
    # hash it directly and compare it with the already authenticated source.
    digest = hashlib.sha256()
    size = 0
    with destination.open("rb") as handle:
        while chunk := handle.read(CHUNK_SIZE):
            size += len(chunk)
            digest.update(chunk)
        os.fsync(handle.fileno())
    if size != record["size"] or digest.hexdigest() != record["sha256"]:
        fail(f"copied {label} does not match its source snapshot: {source}")
    validate_source_file_unchanged(source, record, label)
    os.chmod(destination, 0o444)


def write_durable(path: Path, payload: bytes, mode: int = 0o444) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())
    os.chmod(path, mode)


def fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def make_tree_read_only(root: Path) -> None:
    for current_root, dirs, files in os.walk(root, topdown=False, followlinks=False):
        current = Path(current_root)
        for name in files:
            item = current / name
            if item.is_symlink():
                fail(f"generated union unexpectedly contains a symlink: {item}")
            os.chmod(item, 0o444)
        for name in dirs:
            item = current / name
            if item.is_symlink():
                fail(f"generated union unexpectedly contains a symlink: {item}")
            os.chmod(item, 0o555)
        os.chmod(current, 0o555)
        fsync_directory(current)


def load_clips(payload: bytes, map_path: Path) -> dict[str, dict[str, Any]]:
    try:
        decoded = json.loads(payload)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        fail(f"invalid JSON object map {map_path}: {exc}")
    clips = decoded.get("clips", decoded) if isinstance(decoded, dict) else None
    if not isinstance(clips, dict) or not clips:
        fail(f"invalid or empty object map: {map_path}")
    normalized: dict[str, dict[str, Any]] = {}
    for raw_clip_id, entry in clips.items():
        clip_id = str(raw_clip_id).strip()
        if not clip_id or clip_id != raw_clip_id or "/" in clip_id or "\\" in clip_id:
            fail(f"invalid clip id in {map_path}: {raw_clip_id!r}")
        if not isinstance(entry, dict):
            fail(f"object-map entry for {clip_id} must be an object: {map_path}")
        normalized[clip_id] = dict(entry)
    return normalized


def resolve_asset(
    raw: Any,
    source_dir: Path,
    data_root: Path,
    label: str,
) -> Path:
    if not isinstance(raw, str) or not raw.strip():
        fail(f"{label} must be a non-empty path string")
    candidate = Path(raw).expanduser()
    if not candidate.is_absolute():
        candidate = source_dir / candidate
    candidate = lexical_path(candidate)
    require_owned_path(candidate, data_root, label, strict=True)
    reject_symlink_components(candidate, data_root, label, include_leaf=True)
    if not candidate.is_file():
        fail(f"missing {label}: {candidate}")
    return candidate


def validate_generation_structure(generation: Path, generation_root: Path) -> dict[str, Any]:
    if generation.is_symlink() or not generation.is_dir() or generation.parent != generation_root:
        fail(f"invalid realdata union generation path: {generation}")
    marker = generation / MARKER_NAME
    manifest_path = generation / MANIFEST_NAME
    if marker.is_symlink() or not marker.is_file():
        fail(f"realdata union generation is incomplete (missing marker): {generation}")
    if manifest_path.is_symlink() or not manifest_path.is_file():
        fail(f"realdata union generation is incomplete (missing manifest): {generation}")
    try:
        marker_text = marker.read_text(encoding="utf-8")
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"invalid realdata union generation manifest {manifest_path}: {exc}")
    if marker_text != LEGACY_MARKER_TEXT:
        fail(f"realdata union generation has an invalid ownership marker: {generation}")
    if manifest.get("generator") != GENERATOR:
        fail(f"realdata union generation has an unexpected owner: {generation}")
    if manifest.get("schema_version") != GENERATION_SCHEMA_VERSION:
        fail(f"realdata union generation has an unsupported schema: {generation}")
    if manifest.get("generation_id") != generation.name:
        fail(f"realdata union generation id/path mismatch: {generation}")
    if len(generation.name) != 64 or any(char not in "0123456789abcdef" for char in generation.name):
        fail(f"invalid content-addressed generation name: {generation.name}")
    identity = {
        "schema_version": manifest.get("schema_version"),
        "generator": manifest.get("generator"),
        "map_core_sha256": manifest.get("map_core_sha256"),
        "source_files": manifest.get("source_files"),
    }
    if sha256_bytes(canonical_json_bytes(identity)) != generation.name:
        fail(f"realdata union generation manifest does not match its content address: {generation}")
    generation_files = manifest.get("generation_files")
    if not isinstance(generation_files, list) or not generation_files:
        fail(f"realdata union generation has no authenticated file inventory: {generation}")
    seen_paths: set[str] = set()
    for record in generation_files:
        if not isinstance(record, dict):
            fail(f"invalid generated-file record in {manifest_path}")
        raw_relative = record.get("path")
        if not isinstance(raw_relative, str) or not raw_relative:
            fail(f"invalid generated-file path in {manifest_path}: {raw_relative!r}")
        relative = Path(raw_relative)
        if relative.is_absolute() or ".." in relative.parts or relative.as_posix() != raw_relative:
            fail(f"unsafe generated-file path in {manifest_path}: {raw_relative!r}")
        if raw_relative in seen_paths:
            fail(f"duplicate generated-file path in {manifest_path}: {raw_relative}")
        seen_paths.add(raw_relative)
        candidate = generation / relative
        reject_symlink_components(
            candidate,
            generation,
            f"generated union file {raw_relative}",
            include_leaf=True,
        )
        if not candidate.is_file():
            fail(f"realdata union generation is incomplete: {candidate}")
        if not isinstance(record.get("size"), int) or record["size"] < 0:
            fail(f"invalid generated-file size in {manifest_path}: {raw_relative}")
        digest = record.get("sha256")
        if not isinstance(digest, str) or len(digest) != 64 or any(
            char not in "0123456789abcdef" for char in digest
        ):
            fail(f"invalid generated-file digest in {manifest_path}: {raw_relative}")
    if "_clip_object_urdf_map.json" not in seen_paths:
        fail(f"generated union inventory omits its object map: {manifest_path}")
    return manifest


def validate_existing_alias(alias: Path, generation_root: Path) -> str:
    if not os.path.lexists(alias):
        return "missing"
    if alias.is_symlink():
        try:
            target = alias.resolve(strict=True)
        except (OSError, RuntimeError) as exc:
            fail(f"realdata union alias is dangling or cyclic: {alias}: {exc}")
        if target.parent != generation_root:
            fail(
                f"realdata union alias escapes its owned generation root: {alias} -> {target}; "
                "aliases to /nfs or other roots are forbidden"
            )
        validate_generation_structure(target, generation_root)
        return "symlink"
    if alias.is_dir():
        marker = alias / MARKER_NAME
        object_map = alias / "_clip_object_urdf_map.json"
        if marker.is_symlink() or not marker.is_file() or object_map.is_symlink() or not object_map.is_file():
            fail(
                f"refusing to replace non-generated realdata union directory: {alias}. "
                "Choose an empty REALDATA_UNION_DIR."
            )
        try:
            marker_text = marker.read_text(encoding="utf-8")
            legacy_map = json.loads(object_map.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            fail(f"could not validate legacy generated union {alias}: {exc}")
        if (
            marker_text != LEGACY_MARKER_TEXT
            or not isinstance(legacy_map, dict)
            or legacy_map.get("notes")
            != "Generated symlink union for corl_numbers/train_as_general_realdata.sh."
        ):
            fail(f"refusing to replace unrecognized legacy union directory: {alias}")
        for child in alias.iterdir():
            if child.name in {MARKER_NAME, "_clip_object_urdf_map.json"}:
                continue
            if child.suffix == ".npz" and child.is_symlink():
                continue
            if child.name == "contact_export_from_retarget" and child.is_dir() and not any(
                child.iterdir()
            ):
                continue
            fail(
                f"legacy union contains non-view data that will not be deleted: {child}. "
                "Move it out of REALDATA_UNION_DIR and rerun."
            )
        return "legacy-directory"
    fail(f"REALDATA_UNION_DIR must be absent, a generated alias, or a legacy generated directory: {alias}")


def rename_exchange(left: Path, right: Path) -> None:
    libc = ctypes.CDLL(None, use_errno=True)
    renameat2 = getattr(libc, "renameat2", None)
    if renameat2 is None:
        fail(
            "atomic migration of the legacy realdata union requires Linux renameat2; "
            "remove the legacy generated directory explicitly and rerun"
        )
    renameat2.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint]
    renameat2.restype = ctypes.c_int
    at_fdcwd = -100
    rename_exchange_flag = 2
    result = renameat2(
        at_fdcwd,
        os.fsencode(left),
        at_fdcwd,
        os.fsencode(right),
        rename_exchange_flag,
    )
    if result != 0:
        errno_value = ctypes.get_errno()
        fail(f"atomic legacy-union migration failed: {os.strerror(errno_value)}")


def publish_alias(alias: Path, generation: Path, generation_root: Path) -> None:
    state = validate_existing_alias(alias, generation_root)
    temporary = alias.parent / f".{alias.name}.publish-{os.getpid()}-{uuid.uuid4().hex}"
    relative_target = os.path.relpath(generation, alias.parent)
    os.symlink(relative_target, temporary, target_is_directory=True)
    try:
        if state in {"missing", "symlink"}:
            os.replace(temporary, alias)
        elif state == "legacy-directory":
            rename_exchange(temporary, alias)
            # After RENAME_EXCHANGE the old legacy directory is parked at the
            # private temporary path.  The public name already points at the
            # complete generation, so cleanup cannot expose a partial union.
            shutil.rmtree(temporary)
        else:  # pragma: no cover - exhaustive guard
            fail(f"unsupported alias state: {state}")
        fsync_directory(alias.parent)
    finally:
        if temporary.is_symlink():
            temporary.unlink()
        elif temporary.exists():
            fail(f"legacy generated union cleanup was incomplete: {temporary}")
    target = alias.resolve(strict=True)
    if target != generation:
        fail(f"atomic realdata union publication selected an unexpected target: {target}")


repo_root = Path(sys.argv[1]).expanduser().resolve(strict=True)
data_root = lexical_path(sys.argv[2])
expected_data_root = repo_root / "data"
if data_root != expected_data_root:
    fail(f"LOCAL_DATA_ROOT must be exactly the repository data directory: {expected_data_root}")
if data_root.is_symlink() or not data_root.is_dir() or data_root.resolve(strict=True) != data_root:
    fail(f"repository data directory must be a real local directory, not an alias: {data_root}")

source_dirs: list[Path] = []
for raw_source in sys.argv[3:5]:
    source = lexical_path(raw_source)
    require_owned_path(source, data_root, "realdata source directory", strict=True)
    reject_symlink_components(source, data_root, "realdata source directory", include_leaf=True)
    if not source.is_dir():
        fail(f"missing realdata source directory: {source}. Run ./cp_baseline.sh first.")
    source_dirs.append(source)
if source_dirs[0] == source_dirs[1]:
    fail(f"the two realdata source directories must be distinct: {source_dirs[0]}")

out_alias = lexical_path(sys.argv[5])
require_owned_path(out_alias, data_root, "realdata union alias", strict=True)
reject_symlink_components(out_alias, data_root, "realdata union alias parent", include_leaf=False)
generation_root = out_alias.parent / f"_{out_alias.name}_generations"
require_owned_path(generation_root, data_root, "realdata generation root", strict=True)
reject_symlink_components(generation_root, data_root, "realdata generation root", include_leaf=True)
if generation_root.exists() and not generation_root.is_dir():
    fail(f"realdata generation root must be a directory: {generation_root}")

contact_root = lexical_path(sys.argv[6])
require_owned_path(contact_root, data_root, "REALDATA_CONTACT_EXPORT_ROOT", strict=True)
reject_symlink_components(contact_root, data_root, "REALDATA_CONTACT_EXPORT_ROOT", include_leaf=True)
if contact_root.exists() and not contact_root.is_dir():
    fail(f"REALDATA_CONTACT_EXPORT_ROOT must be a directory: {contact_root}")

single_slot_base = lexical_path(sys.argv[7])
require_owned_path(single_slot_base, data_root, "AS_SINGLE_SLOT_MOTION_BASE", strict=True)
reject_symlink_components(
    single_slot_base,
    data_root,
    "AS_SINGLE_SLOT_MOTION_BASE",
    include_leaf=True,
)
if single_slot_base.exists() and not single_slot_base.is_dir():
    fail(f"AS_SINGLE_SLOT_MOTION_BASE must be a directory: {single_slot_base}")
try:
    expected_total = int(sys.argv[8])
except ValueError:
    fail(f"AS_EXPECTED_TOTAL must be a positive integer, got {sys.argv[8]!r}")
if str(expected_total) != sys.argv[8] or expected_total <= 0:
    fail(f"AS_EXPECTED_TOTAL must be a canonical positive integer, got {sys.argv[8]!r}")

for source_dir in source_dirs:
    if paths_overlap(out_alias, source_dir) or paths_overlap(generation_root, source_dir):
        fail(f"realdata source and generated union namespaces overlap: {source_dir}")
    if paths_overlap(contact_root, source_dir):
        fail(f"REALDATA_CONTACT_EXPORT_ROOT overlaps immutable source data: {contact_root}")
if paths_overlap(contact_root, out_alias) or paths_overlap(contact_root, generation_root):
    fail(
        "REALDATA_CONTACT_EXPORT_ROOT must be outside the immutable union alias and "
        f"generation namespace: {contact_root}"
    )
for immutable_path in [*source_dirs, out_alias, generation_root]:
    if paths_overlap(single_slot_base, immutable_path):
        fail(
            "AS_SINGLE_SLOT_MOTION_BASE must be outside source and immutable union "
            f"namespaces: {single_slot_base}"
        )
if paths_overlap(single_slot_base, contact_root):
    fail(
        "AS_SINGLE_SLOT_MOTION_BASE and REALDATA_CONTACT_EXPORT_ROOT must be disjoint: "
        f"{single_slot_base}"
    )

# Validate any currently published alias before reading or writing generation
# state.  In particular, an alias that escapes to /nfs fails closed and is
# never replaced opportunistically.
validate_existing_alias(out_alias, generation_root)

merged_clips: dict[str, dict[str, Any]] = {}
clip_sources: dict[str, Path] = {}
source_counts: dict[str, int] = {}
source_records: dict[Path, dict[str, Any]] = {}
asset_destinations: dict[Path, Path] = {}

for source_dir in source_dirs:
    source_rel = source_dir.relative_to(data_root).as_posix()
    map_path = source_dir / "_clip_object_urdf_map.json"
    map_bytes, map_record = stable_read_bytes(map_path, data_root, "object map")
    source_records[map_path] = map_record
    clips = load_clips(map_bytes, map_path)
    npz_files = sorted(source_dir.glob("*.npz"), key=lambda path: path.name)
    if not npz_files:
        fail(f"no .npz clips found in realdata source directory: {source_dir}")
    npz_ids = {path.stem for path in npz_files}
    map_ids = set(clips)
    if npz_ids != map_ids:
        missing = sorted(npz_ids - map_ids)
        extra = sorted(map_ids - npz_ids)
        fail(
            f"object map and .npz clips are not an exact set in {source_dir}; "
            f"missing_entries={missing[:10]} stale_entries={extra[:10]}"
        )
    source_counts[source_rel] = len(npz_files)

    for npz_path in npz_files:
        clip_id = npz_path.stem
        if clip_id in merged_clips:
            fail(f"duplicate clip id across realdata sources: {clip_id}")
        npz_record = stable_file_digest(npz_path, data_root, f"motion clip {clip_id}")
        source_records[npz_path] = npz_record
        rewritten = dict(clips[clip_id])
        for key in ("object_urdf_path", "object_mesh_path"):
            if key not in rewritten:
                continue
            asset = resolve_asset(
                rewritten[key],
                source_dir,
                data_root,
                f"{key} asset for clip {clip_id}",
            )
            destination = Path("_source_assets") / asset.relative_to(data_root)
            asset_destinations[asset] = destination
            rewritten[key] = destination.as_posix()
            if asset not in source_records:
                source_records[asset] = stable_file_digest(
                    asset,
                    data_root,
                    f"{key} asset for clip {clip_id}",
                )
        merged_clips[clip_id] = rewritten
        clip_sources[clip_id] = npz_path

if len(merged_clips) != expected_total:
    fail(
        f"realdata union expected {expected_total} clips from AS_EXPECTED_TOTAL, "
        f"found {len(merged_clips)}"
    )

# Re-list each source after hashing so additions/removals during discovery fail
# before a generation directory is created.
for source_dir in source_dirs:
    current_ids = {path.stem for path in source_dir.glob("*.npz")}
    expected_ids = {clip_id for clip_id, path in clip_sources.items() if path.parent == source_dir}
    if current_ids != expected_ids:
        fail(f"realdata source clip set changed during validation: {source_dir}")

source_file_manifest = [
    public_record(source_records[path])
    for path in sorted(source_records, key=lambda item: item.relative_to(data_root).as_posix())
]
map_core = {
    "clips": {clip_id: merged_clips[clip_id] for clip_id in sorted(merged_clips)},
    "source_dirs": [path.relative_to(data_root).as_posix() for path in source_dirs],
    "source_counts": source_counts,
}
identity_payload = {
    "schema_version": GENERATION_SCHEMA_VERSION,
    "generator": GENERATOR,
    "map_core_sha256": sha256_bytes(canonical_json_bytes(map_core)),
    "source_files": source_file_manifest,
}
generation_id = sha256_bytes(canonical_json_bytes(identity_payload))
generation = generation_root / generation_id
map_payload = {
    **map_core,
    "generation": {
        "schema_version": GENERATION_SCHEMA_VERSION,
        "id": generation_id,
        "manifest": MANIFEST_NAME,
    },
    "notes": "Immutable content-addressed CoRL realdata union.",
}
map_output = json.dumps(map_payload, indent=2, sort_keys=True, allow_nan=False).encode("utf-8") + b"\n"

generation_files: list[dict[str, Any]] = []
for clip_id in sorted(clip_sources):
    record = source_records[clip_sources[clip_id]]
    generation_files.append(
        {"path": f"{clip_id}.npz", "size": record["size"], "sha256": record["sha256"]}
    )
for source, destination in sorted(asset_destinations.items(), key=lambda item: item[1].as_posix()):
    record = source_records[source]
    generation_files.append(
        {"path": destination.as_posix(), "size": record["size"], "sha256": record["sha256"]}
    )
generation_files.append(
    {
        "path": "_clip_object_urdf_map.json",
        "size": len(map_output),
        "sha256": sha256_bytes(map_output),
    }
)
manifest = {
    **identity_payload,
    "generation_id": generation_id,
    "clip_count": len(merged_clips),
    "source_counts": source_counts,
    "generation_files": generation_files,
}
manifest_output = json.dumps(manifest, indent=2, sort_keys=True, allow_nan=False).encode("utf-8") + b"\n"

reject_symlink_components(out_alias, data_root, "realdata union alias parent", include_leaf=False)
out_alias.parent.mkdir(parents=True, exist_ok=True)
generation_root.mkdir(parents=True, exist_ok=True)
reject_symlink_components(generation_root, data_root, "realdata generation root", include_leaf=True)
if generation_root.resolve(strict=True) != generation_root:
    fail(f"realdata generation root resolved through an unexpected alias: {generation_root}")

lock_path = generation_root / ".publish.lock"
if lock_path.is_symlink():
    fail(f"realdata publication lock must not be a symlink: {lock_path}")
lock_fd = os.open(
    lock_path,
    os.O_RDWR | os.O_CREAT | os.O_CLOEXEC | getattr(os, "O_NOFOLLOW", 0),
    0o600,
)
if not stat.S_ISREG(os.fstat(lock_fd).st_mode):
    os.close(lock_fd)
    fail(f"realdata publication lock must be a regular file: {lock_path}")
with os.fdopen(lock_fd, "a+b") as lock_handle:
    fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX)
    # A concurrent publisher may have switched this name while we hashed the
    # sources; revalidate before publication.
    validate_existing_alias(out_alias, generation_root)
    for source, record in source_records.items():
        validate_source_file_unchanged(source, record, f"authenticated source file {source}")
    if generation.exists():
        existing = validate_generation_structure(generation, generation_root)
        if existing != manifest:
            fail(f"existing generation manifest does not match its content address: {generation}")
        for expected in generation_files:
            candidate = generation / expected["path"]
            if candidate.is_symlink() or not candidate.is_file():
                fail(f"existing generation is incomplete: {candidate}")
            observed = stable_file_digest(
                candidate,
                generation,
                f"generated union file {expected['path']}",
            )
            if public_record(observed) != expected:
                fail(f"existing generation file failed content validation: {candidate}")
    else:
        staging = generation_root / f".{generation_id}.staging-{os.getpid()}-{uuid.uuid4().hex}"
        staging.mkdir(mode=0o700)
        try:
            for clip_id in sorted(clip_sources):
                source = clip_sources[clip_id]
                copy_verified(
                    source,
                    staging / f"{clip_id}.npz",
                    source_records[source],
                    data_root,
                    f"motion clip {clip_id}",
                )
            for source, destination in sorted(
                asset_destinations.items(), key=lambda item: item[1].as_posix()
            ):
                copy_verified(
                    source,
                    staging / destination,
                    source_records[source],
                    data_root,
                    f"object asset {source}",
                )
            write_durable(staging / "_clip_object_urdf_map.json", map_output)
            write_durable(staging / MANIFEST_NAME, manifest_output)
            write_durable(staging / MARKER_NAME, LEGACY_MARKER_TEXT.encode("utf-8"))
            make_tree_read_only(staging)
            fsync_directory(staging)
            os.replace(staging, generation)
            fsync_directory(generation_root)
        except BaseException:
            if staging.exists():
                os.chmod(staging, 0o700)
                for current_root, dirs, files in os.walk(staging):
                    for name in dirs:
                        os.chmod(Path(current_root) / name, 0o700)
                    for name in files:
                        os.chmod(Path(current_root) / name, 0o600)
                shutil.rmtree(staging)
            raise

    for source, record in source_records.items():
        validate_source_file_unchanged(source, record, f"authenticated source file {source}")
    publish_alias(out_alias, generation, generation_root)
    reject_symlink_components(
        contact_root,
        data_root,
        "REALDATA_CONTACT_EXPORT_ROOT",
        include_leaf=True,
    )
    contact_root.mkdir(parents=True, exist_ok=True)
    reject_symlink_components(
        contact_root,
        data_root,
        "REALDATA_CONTACT_EXPORT_ROOT",
        include_leaf=True,
    )
    if contact_root.resolve(strict=True) != contact_root:
        fail(f"REALDATA_CONTACT_EXPORT_ROOT resolved through an unexpected alias: {contact_root}")

print(
    f"[INFO] Prepared CoRL realdata union: {out_alias} -> {generation} "
    f"({len(merged_clips)} clips, generation={generation_id})"
)
PY

export AS_DATA_DIR="${REALDATA_UNION_DIR}"
export AS_OBJECT_MAP="${REALDATA_UNION_DIR}/_clip_object_urdf_map.json"
export AS_EXPECTED_TOTAL
export AS_SINGLE_SLOT_MOTION_BASE
export REWARD_CONFIG
case "$(echo "${REWARD_CONFIG}" | tr '[:upper:]_' '[:lower:]-')" in
  *offline-contact-guidance*)
    export CONTACT_EXPORT_ROOT="${REALDATA_CONTACT_EXPORT_ROOT}"
    export HOLOSOMA_REQUIRE_CONTACT_INTERVAL_COVERAGE=1
    export HOLOSOMA_REQUIRE_CONTACT_TARGET_COVERAGE=1
    ;;
  *)
    unset CONTACT_EXPORT_ROOT AS_CONTACT_EXPORT_ROOT
    export HOLOSOMA_REQUIRE_CONTACT_INTERVAL_COVERAGE=${HOLOSOMA_REQUIRE_CONTACT_INTERVAL_COVERAGE:-0}
    export HOLOSOMA_REQUIRE_CONTACT_TARGET_COVERAGE=${HOLOSOMA_REQUIRE_CONTACT_TARGET_COVERAGE:-0}
    ;;
esac
export SEQUENCE_NAME=${SEQUENCE_NAME:-as-general-realdata-corl}

exec bash "${REPO_ROOT}/train_as_general.sh" "$@"
