# @package _global_

defaults:
  - task_base

task:
  type: "whole_body_tracking"
  name: "whole_body_tracking"
  description: "Whole body tracking simulation environment"

  # Interface
  DOMAIN_ID: 0
  INTERFACE: "lo"

  # Joystick
  USE_JOYSTICK: false
  JOYSTICK_TYPE: "xbox"
  JOYSTICK_DEVICE: 0
  
  sim_env:
    _target_: holosoma_inference.sim.BaseSimulator
    config:
      ROBOT_SCENE: ${robot.ROBOT_SCENE_XML}
      SIMULATE_DT: 0.001 
      RATE_LIMIT_DT: 0.001

  policy:
    _target_: holosoma_inference.policies.wbt.WholeBodyTrackingPolicy
    config:
      ROBOT_CFG: ${robot}
      OBS_CFG: ${obs}
      use_sim_time: false
      USE_PHASE: false

    policy_action_scale: 1.0
    # NOTE: When running sim2sim, rl_rate should be set to 50/(RATE_LIMIT_DT/SIMULATE_DT)
    rl_rate: 50
