# @package _global_

defaults:
  - obs_base

obs:
  obs_dict:
    actor_obs:
      - motion_command
      - motion_ref_ori_b
      - base_ang_vel
      - dof_pos
      - dof_vel
      - actions

  history_length_dict:
    actor_obs: 1

  obs_dims:
    motion_command: 29 
    motion_ref_pos_b: 3
    motion_ref_ori_b: 6
    base_lin_vel: 3
    base_ang_vel: 3
    dof_pos: 29
    dof_vel: 29
    actions: 29

  obs_scales: {
    actions: 1.0,
    motion_command: 1.0,
    motion_ref_pos_b: 1.0,
    motion_ref_ori_b: 1.0,
    base_lin_vel: 1.0,
    base_ang_vel: 1.0,
    dof_pos: 1.0,
    dof_vel: 1.0,
    robot_body_pos_b: 1.0,
    robot_body_ori_b: 1.0,
  }
