# @package _global_

robot:
  ROBOT: "t1"
  ROBOT_TYPE: 't1_29dof'
  ASSET_ROOT: "@holosoma_inference/data/robots/t1"
  ASSET_FILE: "@holosoma_inference/data/robots/t1/t1_29dof.urdf"
  ROBOT_SCENE_XML: "@holosoma_inference/data/robots/t1/t1_29dof.xml"
  SDK_TYPE: "booster"
  MOTOR_TYPE: "serial"
  USE_SENSOR: False

  # Number of motors and joints
  NUM_MOTORS: 29
  NUM_JOINTS: 29
  NUM_UPPER_BODY_JOINTS: 16

  # Control gains
  MOTOR_KP: [
    5, 5, 
    20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 20, 20, 20,
    200,
    200, 200, 200, 200, 50, 50,
    200, 200, 200, 200, 50, 50,
  ]
  MOTOR_KD: [
    0.5, 0.5, 
    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
    5.0,
    5.0, 5.0, 5.0, 5.0, 3.0, 3.0,
    5.0, 5.0, 5.0, 5.0, 3.0, 3.0,
  ]

  # Default DOF and motor angles
  DEFAULT_DOF_ANGLES: [
    0.0,  # AAHead_yaw
    0.0,  # Head_pitch
    0.2,  # Left_Shoulder_Pitch
    -1.35,  # Left_Shoulder_Roll
    0.0,  # Left_Elbow_Pitch
    -0.5,  # Left_Elbow_Yaw
    0.0,  # Left_Wrist_Pitch
    0.0,  # Left_Wrist_Yaw
    0.0,  # Left_Hand_Roll
    0.2,  # Right_Shoulder_Pitch
    1.35,  # Right_Shoulder_Roll
    0.0,  # Right_Elbow_Pitch
    0.5,  # Right_Elbow_Yaw
    0.0,  # Right_Wrist_Pitch
    0.0,  # Right_Wrist_Yaw
    0.0,  # Right_Hand_Roll
    0.0,  # Waist
    -0.2,  # Left_Hip_Pitch
    0.0,  # Left_Hip_Roll
    0.0,  # Left_Hip_Yaw
    0.4,  # Left_Knee_Pitch
    -0.25, # Left_Ankle_Pitch
    0.0,  # Left_Ankle_Roll
    -0.2,  # Right_Hip_Pitch
    0.0,  # Right_Hip_Roll
    0.0,  # Right_Hip_Yaw
    0.4,  # Right_Knee_Pitch
    -0.25, # Right_Ankle_Pitch
    0.0,  # Right_Ankle_Roll
  ]
  DEFAULT_MOTOR_ANGLES: [
    0.0,  # AAHead_yaw
    0.0,  # Head_pitch
    0.2,  # Left_Shoulder_Pitch
    -1.35,  # Left_Shoulder_Roll
    0.0,  # Left_Elbow_Pitch
    -0.5,  # Left_Elbow_Yaw
    0.0,  # Left_Wrist_Pitch
    0.0,  # Left_Wrist_Yaw
    0.0,  # Left_Hand_Roll
    0.2,  # Right_Shoulder_Pitch
    1.35,  # Right_Shoulder_Roll
    0.0,  # Right_Elbow_Pitch
    0.5,  # Right_Elbow_Yaw
    0.0,  # Right_Wrist_Pitch
    0.0,  # Right_Wrist_Yaw
    0.0,  # Right_Hand_Roll
    0.0,  # Waist
    -0.2,  # Left_Hip_Pitch
    0.0,  # Left_Hip_Roll
    0.0,  # Left_Hip_Yaw
    0.4,  # Left_Knee_Pitch
    -0.25, # Left_Ankle_Pitch
    0.0,  # Left_Ankle_Roll
    -0.2,  # Right_Hip_Pitch
    0.0,  # Right_Hip_Roll
    0.0,  # Right_Hip_Yaw
    0.4,  # Right_Knee_Pitch
    -0.25, # Right_Ankle_Pitch
    0.0,  # Right_Ankle_Roll
  ]

  # Motor limits
  joint_pos_lower_limit_list: [-1.57, -0.35,
                               -3.31, -1.74, -2.27, -2.27, -2.27, -2.27, -2.27,
                               -3.31, -1.57, -2.27, -2.27, -2.27, -2.27, -2.27,
                               -1.57,
                               -1.8, -0.3, -1, 0, -0.87, -0.44, 
                               -1.8, -1.57, -1, 0, -0.87, -0.44]
  joint_pos_upper_limit_list: [1.57, 1.22,
                               1.22, 1.57, 2.27, 2.27, 2.27, 2.27, 2.27,
                               1.22, 1.74, 2.27, 2.27, 2.27, 2.27, 2.27,
                               1.57,
                               1.57, 1.57, 1, 2.34, 0.35, 0.44,
                               1.57, 0.3, 1, 2.34, 0.35, 0.44]
  joint_vel_limit_list: [12.56, 12.56,
                         18.84, 18.84, 18.84, 18.84, 18.84, 18.84, 18.84,
                         18.84, 18.84, 18.84, 18.84, 18.84, 18.84, 18.84,
                         10.88,
                         12.5, 10.9, 10.9, 11.7, 18.8, 12.4,
                         12.5, 10.9, 10.9, 11.7, 18.8, 12.4]
  motor_effort_limit_list: [7, 7,
                            18, 18, 18, 18, 18, 18, 18,
                            18, 18, 18, 18, 18, 18, 18,
                            30,
                            45, 30, 30, 60, 12, 12,
                            45, 30, 30, 60, 12, 12]

  # Motor to joint mapping
  MOTOR2JOINT: [0, 1, 
                2, 3, 4, 5, 6, 7, 8,
                9, 10, 11, 12, 13, 14, 15, 
                16, 
                17, 18, 19, 20, 21, 22,
                23, 24, 25, 26, 27, 28]
  JOINT2MOTOR: [0, 1, 
                2, 3, 4, 5, 6, 7, 8,
                9, 10, 11, 12, 13, 14, 15,
                16,
                17, 18, 19, 20, 21, 22,
                23, 24, 25, 26, 27, 28]

  # Torso link name
  torso_link_name: "Trunk"

  # Joint names
  dof_names: ['AAHead_yaw', 'Head_pitch',
              'Left_Shoulder_Pitch', 'Left_Shoulder_Roll', 'Left_Elbow_Pitch', 'Left_Elbow_Yaw', 'Left_Wrist_Pitch', 'Left_Wrist_Yaw', 'Left_Hand_Roll',
              'Right_Shoulder_Pitch', 'Right_Shoulder_Roll', 'Right_Elbow_Pitch', 'Right_Elbow_Yaw', 'Right_Wrist_Pitch', 'Right_Wrist_Yaw', 'Right_Hand_Roll',
              'Waist',
              'Left_Hip_Pitch', 'Left_Hip_Roll', 'Left_Hip_Yaw', 'Left_Knee_Pitch', 'Left_Ankle_Pitch', 'Left_Ankle_Roll',
              'Right_Hip_Pitch', 'Right_Hip_Roll', 'Right_Hip_Yaw', 'Right_Knee_Pitch', 'Right_Ankle_Pitch', 'Right_Ankle_Roll']
  dof_names_upper_body: ['AAHead_yaw', 'Head_pitch',
                         'Left_Shoulder_Pitch', 'Left_Shoulder_Roll', 'Left_Elbow_Pitch', 'Left_Elbow_Yaw', 'Left_Wrist_Pitch', 'Left_Wrist_Yaw', 'Left_Hand_Roll',
                         'Right_Shoulder_Pitch', 'Right_Shoulder_Roll', 'Right_Elbow_Pitch', 'Right_Elbow_Yaw', 'Right_Wrist_Pitch', 'Right_Wrist_Yaw', 'Right_Hand_Roll']
  dof_names_lower_body: ['Waist',
                         'Left_Hip_Pitch', 'Left_Hip_Roll', 'Left_Hip_Yaw', 'Left_Knee_Pitch', 'Left_Ankle_Pitch', 'Left_Ankle_Roll',
                         'Right_Hip_Pitch', 'Right_Hip_Roll', 'Right_Hip_Yaw', 'Right_Knee_Pitch', 'Right_Ankle_Pitch', 'Right_Ankle_Roll']
  dof_names_parallel_mech: ['Left_Ankle_Pitch', 'Left_Ankle_Roll', 'Right_Ankle_Pitch', 'Right_Ankle_Roll']

  # Prepare parameters
  prepare:
    stiffness: [
      5., 5.,
      40., 50., 20., 10., 10., 10., 10.,
      40., 50., 20., 10., 10., 10., 10.,
      100., 
      350., 350., 180., 350., 450., 450.,
      350., 350., 180., 350., 450., 450.,
    ]
    damping: [
      0.1, 0.1,
      0.5, 1.5, 0.2, 0.2, 0.2, 0.2, 0.2,
      0.5, 1.5, 0.2, 0.2, 0.2, 0.2, 0.2,
      5.0,
      7.5, 7.5, 3., 5.5, 0.5, 0.5,
      7.5, 7.5, 3., 5.5, 0.5, 0.5,
    ]
    default_qpos: [
      0.0,  0.0,
      0.25, -1.4, 0.0, -0.5, 0.0, 0.0, 0.0,
      0.25, 1.4, 0.0, 0.5, 0.0, 0.0, 0.0,
      0.0,
      -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
      -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
    ]