#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${SCRIPT_DIR}"

cat >&2 <<'EOF'
[ERROR] launch_teacher_as_rollout_8gpu_32env.sh is quarantined.
It rebuilds consumable outputs in place, resolves the teacher independently per
shard, and records hard-coded metadata that can disagree with launch overrides.
Use scripts/launch_teacher_as_realmesh_rollout.sh; it enforces immutable teacher
identity, shard-summary equality, and atomic content-addressed publication.
EOF
exit 2

RUN_ID="${RUN_ID:-as_teacher_rollout_8gpu32env_$(date -u +%Y%m%d_%H%M%S)_bcleb5oi_model58000_195_final0p5_primitiveproj}"
NUM_SHARDS="${NUM_SHARDS:-8}"
PER_GPU_ENVS="${PER_GPU_ENVS:-32}"
GPU_LIST="${GPU_LIST:-0,1,2,3,4,5,6,7}"
PYTHON_BIN="${PYTHON_BIN:-python}"
LOCAL_RANK_OFFSET="${LOCAL_RANK_OFFSET:-20}"

TEACHER_CHECKPOINT="${TEACHER_CHECKPOINT:-wandb://zihanw22/carry-any/bcleb5oi/model_58000.pt}"
SOURCE_AS_DATA_DIR="${SOURCE_AS_DATA_DIR:-${SCRIPT_DIR}/data/ds_as_data/carryany_filter_scale_noscale_keep169_20260513_plus_box_teacher_rollout}"
SOURCE_AS_OBJECT_MAP="${SOURCE_AS_OBJECT_MAP:-${SOURCE_AS_DATA_DIR}/_clip_object_urdf_map.json}"
SOURCE_EXPECTED_TOTAL="${SOURCE_EXPECTED_TOTAL:-195}"
export SOURCE_EXPECTED_TOTAL
SHARD_ROOT="${SHARD_ROOT:-${SCRIPT_DIR}/data/ds_as_data/_teacher_rollout_shards/${RUN_ID}}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${SCRIPT_DIR}/outputs/teacher_as_contacts/${RUN_ID}}"
LOG_ROOT="${LOG_ROOT:-${SCRIPT_DIR}/logs/runtime/${RUN_ID}}"

SUCCESS_POSITION_THRESHOLD="${SUCCESS_POSITION_THRESHOLD:-0.5}"
MIN_CONTACT_FRAMES="${MIN_CONTACT_FRAMES:-10}"
CONTACT_FORCE_THRESHOLD="${CONTACT_FORCE_THRESHOLD:-1.0}"
CONTACT_VOXEL_SIZE="${CONTACT_VOXEL_SIZE:-0.01}"
PHYSX_GPU_COLLISION_STACK_SIZE="${PHYSX_GPU_COLLISION_STACK_SIZE:-268435456}"

IFS=',' read -r -a GPUS <<< "${GPU_LIST}"
if [[ "${#GPUS[@]}" -ne "${NUM_SHARDS}" ]]; then
  echo "[ERROR] GPU_LIST must contain NUM_SHARDS entries. GPU_LIST=${GPU_LIST} NUM_SHARDS=${NUM_SHARDS}" >&2
  exit 2
fi

mkdir -p "${SHARD_ROOT}" "${OUTPUT_ROOT}/shards" "${LOG_ROOT}"

"${PYTHON_BIN}" - "${SOURCE_AS_DATA_DIR}" "${SOURCE_AS_OBJECT_MAP}" "${SHARD_ROOT}" "${NUM_SHARDS}" "${PER_GPU_ENVS}" "${SOURCE_EXPECTED_TOTAL}" <<'PY'
from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

source_dir = Path(sys.argv[1]).expanduser().resolve()
source_map = Path(sys.argv[2]).expanduser().resolve()
shard_root = Path(sys.argv[3]).expanduser().resolve()
num_shards = int(sys.argv[4])
per_gpu_envs = int(sys.argv[5])
expected_total = int(sys.argv[6])

npz_files = sorted(source_dir.glob("*.npz"))
if len(npz_files) != expected_total:
    raise SystemExit(f"[ERROR] Expected {expected_total} source .npz files, found {len(npz_files)} under {source_dir}")
if not source_map.is_file():
    raise SystemExit(f"[ERROR] Missing object map: {source_map}")

payload = json.loads(source_map.read_text(encoding="utf-8"))
metadata = {key: value for key, value in payload.items() if key != "clips"} if isinstance(payload, dict) else {}
clips = payload.get("clips", payload) if isinstance(payload, dict) else payload
if not isinstance(clips, dict) or len(clips) != expected_total:
    raise SystemExit(f"[ERROR] Expected {expected_total} object-map entries, found {len(clips) if isinstance(clips, dict) else 'invalid'}")

missing = [path.stem for path in npz_files if path.stem not in clips]
if missing:
    raise SystemExit(f"[ERROR] Missing object-map entries for source clips: {missing[:10]}")

if shard_root.exists():
    marker = shard_root / ".generated_teacher_rollout_shards"
    existing_children = list(shard_root.iterdir())
    if existing_children and not marker.exists():
        raise SystemExit(f"[ERROR] Refusing to reuse non-generated shard root: {shard_root}")
    for child in existing_children:
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()
else:
    shard_root.mkdir(parents=True)
(shard_root / ".generated_teacher_rollout_shards").write_text("generated by launch_teacher_as_rollout_8gpu_32env.sh\n", encoding="utf-8")

clip_ids = [path.stem for path in npz_files]
base, rem = divmod(len(clip_ids), num_shards)
offset = 0
manifest = {
    "source_as_data_dir": str(source_dir),
    "source_as_object_map": str(source_map),
    "num_shards": num_shards,
    "per_gpu_envs": per_gpu_envs,
    "total_clips": len(clip_ids),
    "shards": [],
}
for shard_idx in range(num_shards):
    count = base + (1 if shard_idx < rem else 0)
    shard_ids = clip_ids[offset : offset + count]
    offset += count
    if count > per_gpu_envs:
        raise SystemExit(f"[ERROR] Shard {shard_idx} has {count} clips, above PER_GPU_ENVS={per_gpu_envs}")

    shard_dir = shard_root / f"shard_{shard_idx:02d}"
    shard_dir.mkdir(parents=True)
    objects_link = shard_dir / "objects"
    try:
        objects_link.symlink_to((source_dir / "objects").resolve(), target_is_directory=True)
    except FileExistsError:
        pass

    for clip_id in shard_ids:
        (shard_dir / f"{clip_id}.npz").symlink_to((source_dir / f"{clip_id}.npz").resolve())

    shard_payload = dict(metadata)
    shard_payload["clips"] = {clip_id: clips[clip_id] for clip_id in shard_ids}
    (shard_dir / "_clip_object_urdf_map.json").write_text(json.dumps(shard_payload, indent=2, sort_keys=True), encoding="utf-8")
    (shard_dir / "clip_ids.txt").write_text("\n".join(shard_ids) + "\n", encoding="utf-8")
    manifest["shards"].append(
        {
            "shard_index": shard_idx,
            "count": count,
            "motion_dir": str(shard_dir),
            "object_map": str(shard_dir / "_clip_object_urdf_map.json"),
            "first_clip": shard_ids[0] if shard_ids else None,
            "last_clip": shard_ids[-1] if shard_ids else None,
        }
    )

(shard_root / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
print(f"[INFO] Prepared {num_shards} shards under {shard_root}")
for shard in manifest["shards"]:
    print(
        f"[INFO] shard_{shard['shard_index']:02d}: {shard['count']} clips "
        f"({shard['first_clip']}..{shard['last_clip']})"
    )
PY

declare -a PIDS=()
declare -a SHARD_LOGS=()

for shard_idx in $(seq 0 $((NUM_SHARDS - 1))); do
  shard_name="$(printf 'shard_%02d' "${shard_idx}")"
  shard_dir="${SHARD_ROOT}/${shard_name}"
  shard_output="${OUTPUT_ROOT}/shards/${shard_name}"
  shard_log="${LOG_ROOT}/${shard_name}.log"
  gpu="${GPUS[${shard_idx}]}"
  local_rank=$((LOCAL_RANK_OFFSET + shard_idx))
  expected_count="$(wc -l < "${shard_dir}/clip_ids.txt" | tr -d ' ')"
  SHARD_LOGS+=("${shard_log}")

  echo "[INFO] Starting ${shard_name}: gpu=${gpu} local_rank=${local_rank} num_envs=${PER_GPU_ENVS} clips=${expected_count} log=${shard_log}"
  (
    set -euo pipefail
    cd "${SCRIPT_DIR}"
    export HOLOSOMA_DEVICE="cuda:${gpu}"
    export LOCAL_RANK="${local_rank}"
    export AS_DATA_DIR="${shard_dir}"
    export AS_OBJECT_MAP="${shard_dir}/_clip_object_urdf_map.json"
    export AS_EXPECTED_TOTAL="${expected_count}"
    export AS_SINGLE_SLOT_MOTION_DIR="${shard_dir}/_single_slot_motion_bank"
    export NUM_ENVS="${PER_GPU_ENVS}"
    export HEADLESS=True
    export OUTPUT_DIR="${shard_output}"
    export SUCCESS_POSITION_THRESHOLD="${SUCCESS_POSITION_THRESHOLD}"
    export MIN_CONTACT_FRAMES="${MIN_CONTACT_FRAMES}"
    export CONTACT_FORCE_THRESHOLD="${CONTACT_FORCE_THRESHOLD}"
    export CONTACT_VOXEL_SIZE="${CONTACT_VOXEL_SIZE}"
    export PHYSX_GPU_COLLISION_STACK_SIZE="${PHYSX_GPU_COLLISION_STACK_SIZE}"
    export PUBLISH_FOR_INFER_BOX=0
    export LAUNCH_VISER=0
    export VALIDATE_OUTPUT_FORMAT=1
    export PYTHON_BIN="${PYTHON_BIN}"
    bash ./infer_teacher_as_contacts.sh "${TEACHER_CHECKPOINT}" \
      --no-project-contact-to-mesh \
      --no-save-glb \
      --no-save-preview-png \
      --no-save-face-heatmap-png
  ) > "${shard_log}" 2>&1 &
  PIDS+=("$!")
done

status=0
for idx in "${!PIDS[@]}"; do
  pid="${PIDS[$idx]}"
  if wait "${pid}"; then
    echo "[INFO] ${SHARD_LOGS[$idx]} finished"
  else
    echo "[ERROR] ${SHARD_LOGS[$idx]} failed" >&2
    status=1
  fi
done

if [[ "${status}" -ne 0 ]]; then
  echo "[ERROR] At least one shard failed; leaving partial outputs under ${OUTPUT_ROOT}/shards" >&2
  exit "${status}"
fi

"${PYTHON_BIN}" - "${OUTPUT_ROOT}" "${SHARD_ROOT}" "${TEACHER_CHECKPOINT}" "${SUCCESS_POSITION_THRESHOLD}" <<'PY'
from __future__ import annotations

import csv
import json
import os
import shutil
import sys
from pathlib import Path

output_root = Path(sys.argv[1]).expanduser().resolve()
shard_root = Path(sys.argv[2]).expanduser().resolve()
checkpoint = sys.argv[3]
success_position_threshold = float(sys.argv[4])
shards_root = output_root / "shards"
clips_dst = output_root / "clips"
motion_dst = output_root / "motion_bank"
clips_dst.mkdir(parents=True, exist_ok=True)
motion_dst.mkdir(parents=True, exist_ok=True)

summary_rows: list[dict[str, str]] = []
success_ids: list[str] = []
failure_ids: list[str] = []
clip_object_map: dict[str, dict[str, object]] = {}
shard_summaries: list[dict[str, object]] = []

for shard_output in sorted(path for path in shards_root.glob("shard_*") if path.is_dir()):
    clips_src = shard_output / "clips"
    motion_src = shard_output / "motion_bank"
    if not clips_src.is_dir() or not motion_src.is_dir():
        raise SystemExit(f"[ERROR] Shard output missing clips or motion_bank: {shard_output}")

    for clip_dir in sorted(path for path in clips_src.iterdir() if path.is_dir()):
        dst = clips_dst / clip_dir.name
        if dst.exists():
            raise SystemExit(f"[ERROR] Duplicate clip directory while merging: {dst.name}")
        shutil.copytree(clip_dir, dst)

    for path in sorted(motion_src.glob("*.npz")):
        dst = motion_dst / path.name
        if dst.exists():
            raise SystemExit(f"[ERROR] Duplicate motion file while merging: {dst.name}")
        shutil.copy2(path, dst)

    source_map = motion_src / "_clip_object_urdf_map.json"
    if source_map.is_file():
        payload = json.loads(source_map.read_text(encoding="utf-8"))
        clips = payload.get("clips", payload)
        for clip_id, entry in clips.items():
            if clip_id in clip_object_map:
                raise SystemExit(f"[ERROR] Duplicate clip object-map entry while merging: {clip_id}")
            clip_object_map[clip_id] = entry

    summary_csv = shard_output / "summary.csv"
    if summary_csv.is_file():
        with summary_csv.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                summary_rows.append(row)
                if str(row.get("success", "")).lower() == "true":
                    success_ids.append(str(row.get("clip_id", "")))
                else:
                    failure_ids.append(str(row.get("clip_id", "")))

    summary_json = shard_output / "summary.json"
    if summary_json.is_file():
        shard_summaries.append(json.loads(summary_json.read_text(encoding="utf-8")))

clip_dirs = sorted(path for path in clips_dst.iterdir() if path.is_dir())
motion_files = sorted(motion_dst.glob("*.npz"))
expected_total = int(os.environ.get("SOURCE_EXPECTED_TOTAL", "195"))
if len(clip_dirs) != expected_total:
    raise SystemExit(f"[ERROR] Merged output expected {expected_total} clip dirs, found {len(clip_dirs)}")
if len(motion_files) != expected_total:
    raise SystemExit(f"[ERROR] Merged output expected {expected_total} rollout motion files, found {len(motion_files)}")
if len(clip_object_map) != expected_total:
    raise SystemExit(f"[ERROR] Merged output expected {expected_total} object-map entries, found {len(clip_object_map)}")
if len(summary_rows) != expected_total:
    raise SystemExit(f"[ERROR] Merged output expected {expected_total} summary rows, found {len(summary_rows)}")

required_files = (
    "teacher_rollout_reference.npz",
    "primitive_contact_points.npy",
    "primitive_contact_point_counts.npy",
    "contact_intervals.json",
    "contact_intervals.npz",
)
missing: list[str] = []
for clip_dir in clip_dirs:
    for filename in required_files:
        if not (clip_dir / filename).is_file():
            missing.append(f"{clip_dir.name}/{filename}")
if missing:
    raise SystemExit(f"[ERROR] Merged output missing required files: {missing[:20]}")

with (output_root / "summary.csv").open("w", encoding="utf-8", newline="") as f:
    fieldnames = list(summary_rows[0].keys())
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(summary_rows)

(motion_dst / "_clip_object_urdf_map.json").write_text(
    json.dumps({"clips": dict(sorted(clip_object_map.items()))}, indent=2),
    encoding="utf-8",
)
(output_root / "success_clips.txt").write_text("\n".join(success_ids) + ("\n" if success_ids else ""), encoding="utf-8")
(output_root / "failure_clips.txt").write_text("\n".join(failure_ids) + ("\n" if failure_ids else ""), encoding="utf-8")
summary = {
    "checkpoint": checkpoint,
    "saved_wandb_path": "zihanw22/carry-any/bcleb5oi" if "bcleb5oi" in checkpoint else None,
    "num_clips": len(summary_rows),
    "num_success": len(success_ids),
    "num_failure": len(failure_ids),
    "num_batches": len(shard_summaries),
    "num_envs": 32,
    "num_gpus": len(shard_summaries),
    "total_parallel_envs": 32 * len(shard_summaries),
    "shard_root": str(shard_root),
    "shard_outputs": [str(path) for path in sorted(shards_root.glob("shard_*")) if path.is_dir()],
    "export_config": {
        "output_dir": str(output_root),
        "min_contact_frames": 10,
        "contact_force_threshold": 1.0,
        "contact_voxel_size": 0.01,
        "success_position_threshold": success_position_threshold,
        "max_rollout_steps": None,
        "project_contact_to_mesh": False,
        "save_glb": False,
        "save_preview_png": False,
        "save_face_heatmap_png": False,
    },
}
(output_root / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
merge_manifest = {
    "output_root": str(output_root),
    "clip_count": len(clip_dirs),
    "motion_count": len(motion_files),
    "summary_count": len(summary_rows),
    "success_count": len(success_ids),
    "failure_count": len(failure_ids),
}
(output_root / "merge_manifest.json").write_text(json.dumps(merge_manifest, indent=2), encoding="utf-8")
print(f"[INFO] Merged rollout export: {len(clip_dirs)} clips, {len(motion_files)} motion files -> {output_root}")
PY

echo "[INFO] Done: ${OUTPUT_ROOT}"
