#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path
from typing import Any

from prepare_single_slot_object_map import prepare_single_slot_map


def _safe_stem(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_.")
    return cleaned or "clip"


def _load_clip_map(path: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict) and isinstance(payload.get("clips"), dict):
        return {key: value for key, value in payload.items() if key != "clips"}, payload["clips"]
    if isinstance(payload, dict):
        return {}, payload
    raise ValueError(f"Invalid object map payload: {path}")


def _resolve_path(raw: str, base_dir: Path) -> Path:
    path = Path(str(raw).strip()).expanduser()
    if path.is_absolute():
        return path.resolve()
    return (base_dir / path).resolve()


def _resolve_entry(entry: Any, *, clip_id: str, object_map_path: Path) -> tuple[dict[str, Any], Path]:
    if isinstance(entry, str):
        resolved = _resolve_path(entry, object_map_path.parent)
        return {"object_name": "", "object_urdf_path": str(resolved)}, resolved
    if not isinstance(entry, dict):
        raise ValueError(f"Object map entry for {clip_id!r} must be a dict or string.")

    resolved_entry = dict(entry)
    raw_urdf = str(resolved_entry.get("object_urdf_path", "")).strip()
    if not raw_urdf:
        raise ValueError(f"Object map entry for {clip_id!r} has no object_urdf_path.")

    urdf_path = _resolve_path(raw_urdf, object_map_path.parent)
    resolved_entry["object_urdf_path"] = str(urdf_path)

    raw_mesh = str(resolved_entry.get("object_mesh_path", "")).strip()
    if raw_mesh:
        resolved_entry["object_mesh_path"] = str(_resolve_path(raw_mesh, object_map_path.parent))

    return resolved_entry, urdf_path


def _ensure_generated_dir(path: Path, *, force: bool) -> None:
    marker = path / ".generated_by_prepare_as_replay_pairs"
    if path.exists():
        if not marker.exists() and not force:
            raise RuntimeError(
                f"Refusing to reuse non-generated pair directory: {path}. "
                "Pass --force or choose a different --work-root."
            )
        for child in path.iterdir():
            if child.is_dir() and not child.is_symlink():
                shutil.rmtree(child)
            else:
                child.unlink()
    else:
        path.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by scripts/prepare_as_replay_pairs.py\n", encoding="utf-8")


def _symlink_or_copy(src: Path, dst: Path) -> None:
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    try:
        dst.symlink_to(src.resolve())
    except OSError:
        shutil.copy2(src, dst)


def _read_clip_list(path: Path) -> list[str]:
    clips: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        clips.extend(part.strip() for part in line.split(",") if part.strip())
    return clips


def _parse_clip_args(raw_clips: list[str] | None, clip_list: Path | None) -> list[str]:
    clips: list[str] = []
    if raw_clips:
        for raw in raw_clips:
            clips.extend(part.strip() for part in raw.split(",") if part.strip())
    if clip_list is not None:
        clips.extend(_read_clip_list(clip_list))
    return clips


def _select_motion_paths(
    motion_paths: list[Path],
    *,
    requested_clips: list[str],
    clip_regex: str | None,
    start_index: int,
    limit: int | None,
) -> list[Path]:
    by_stem = {path.stem: path for path in motion_paths}
    if requested_clips:
        missing = [clip for clip in requested_clips if clip not in by_stem]
        if missing:
            preview = ", ".join(missing[:10])
            raise ValueError(f"Requested clip(s) not found in motion dir: {preview}")
        selected = [by_stem[clip] for clip in requested_clips]
    elif clip_regex:
        pattern = re.compile(clip_regex)
        selected = [path for path in motion_paths if pattern.search(path.stem)]
    else:
        selected = list(motion_paths)

    if start_index < 0:
        raise ValueError("--start-index must be >= 0")
    selected = selected[start_index:]
    if limit is not None:
        if limit < 0:
            raise ValueError("--limit must be >= 0")
        selected = selected[:limit]
    return selected


def prepare_pairs(args: argparse.Namespace) -> int:
    motion_dir = args.motion_dir.expanduser().resolve()
    object_map = args.object_map.expanduser().resolve()
    work_root = args.work_root.expanduser().resolve()
    video_root = args.video_root.expanduser().resolve()
    manifest = args.manifest.expanduser().resolve()

    if not motion_dir.is_dir():
        raise FileNotFoundError(f"Motion directory does not exist: {motion_dir}")
    if not object_map.is_file():
        raise FileNotFoundError(f"Object map does not exist: {object_map}")

    metadata, clips = _load_clip_map(object_map)
    if not clips:
        raise ValueError(f"Object map has no clips: {object_map}")

    motion_paths = sorted(motion_dir.glob("*.npz"))
    if not motion_paths:
        raise FileNotFoundError(f"No .npz files found in motion directory: {motion_dir}")

    if args.expected_total is not None:
        expected = int(args.expected_total)
        if len(motion_paths) != expected:
            raise ValueError(f"Expected {expected} .npz clips in {motion_dir}, found {len(motion_paths)}")
        if len(clips) != expected:
            raise ValueError(f"Expected {expected} object-map entries in {object_map}, found {len(clips)}")

    requested_clips = _parse_clip_args(args.clip, args.clip_list)
    selected_paths = _select_motion_paths(
        motion_paths,
        requested_clips=requested_clips,
        clip_regex=args.clip_regex,
        start_index=args.start_index,
        limit=args.limit,
    )
    if not selected_paths:
        raise ValueError("No clips selected.")

    work_root.mkdir(parents=True, exist_ok=True)
    video_root.mkdir(parents=True, exist_ok=True)
    manifest.parent.mkdir(parents=True, exist_ok=True)

    rows: list[str] = []
    for index, src_npz in enumerate(selected_paths):
        clip_id = src_npz.stem
        if clip_id not in clips:
            raise ValueError(f"Missing object-map entry for selected clip: {clip_id}")

        resolved_entry, urdf_path = _resolve_entry(clips[clip_id], clip_id=clip_id, object_map_path=object_map)
        if not urdf_path.is_file():
            raise FileNotFoundError(f"Clip {clip_id!r} object URDF does not exist: {urdf_path}")

        pair_name = f"{index:04d}_{_safe_stem(clip_id)}"
        pair_dir = work_root / pair_name
        _ensure_generated_dir(pair_dir, force=args.force)
        _symlink_or_copy(src_npz, pair_dir / src_npz.name)

        pair_map = pair_dir / "_clip_object_urdf_map.json"
        payload = dict(metadata)
        payload["clips"] = {clip_id: resolved_entry}
        pair_map.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

        active_urdf_path = urdf_path
        if args.single_slot:
            prepare_single_slot_map(motion_dir=pair_dir, object_map=pair_map, output_map=pair_map)
            _final_metadata, final_clips = _load_clip_map(pair_map)
            final_entry = final_clips.get(clip_id, {})
            if isinstance(final_entry, dict):
                final_urdf_raw = str(final_entry.get("object_urdf_path", "")).strip()
            else:
                final_urdf_raw = str(final_entry).strip()
            if final_urdf_raw:
                active_urdf_path = _resolve_path(final_urdf_raw, pair_map.parent)

        video_dir = video_root / pair_name
        video_dir.mkdir(parents=True, exist_ok=True)
        rows.append(
            "\t".join(
                [
                    clip_id,
                    str(pair_dir),
                    str(pair_map),
                    str(active_urdf_path),
                    str(src_npz),
                    str(video_dir),
                ]
            )
        )

    manifest.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"[INFO] Prepared {len(rows)} AS replay pair(s).")
    print(f"[INFO] Manifest: {manifest}")
    return len(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare one-clip AS replay banks for Isaac Sim debugging.")
    parser.add_argument("--motion-dir", required=True, type=Path)
    parser.add_argument("--object-map", required=True, type=Path)
    parser.add_argument("--work-root", required=True, type=Path)
    parser.add_argument("--video-root", required=True, type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--expected-total", type=int)
    parser.add_argument("--clip", action="append", help="Clip id or comma-separated clip ids. Can be repeated.")
    parser.add_argument("--clip-list", type=Path, help="Text file with clip ids, one per line or comma-separated.")
    parser.add_argument("--clip-regex", help="Regex used to select clip ids from the sorted motion bank.")
    parser.add_argument("--start-index", type=int, default=0)
    parser.add_argument("--limit", type=int)
    parser.add_argument("--single-slot", action="store_true", help="Canonicalize object URDFs like train_as_general.sh.")
    parser.add_argument("--force", action="store_true", help="Clean and regenerate existing generated pair dirs.")
    args = parser.parse_args()

    try:
        prepare_pairs(args)
    except Exception as exc:
        print(f"[ERROR] {exc}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
