#!/usr/bin/env bash
CLIP="${1:-${HOLOSOMA_MJ_CLIP:-box_75}}"
CLIP="${CLIP%.npz}"
export HOLOSOMA_MJ_CLIP="$CLIP"
export HOLOSOMA_MJ_MOTION="${HOLOSOMA_MJ_MOTION:-data_demo/${CLIP}.npz}"
export HOLOSOMA_MJ_MODEL="${HOLOSOMA_MJ_MODEL:-logs/wandb_runs/shoo7sr1/model_29999.onnx}"
if [ -z "${HOLOSOMA_POLICY_MOTION_INDEX_OFFSET:-}" ]; then
    export HOLOSOMA_POLICY_MOTION_INDEX_OFFSET=1
fi

export PYTHONSAFEPATH=1
export PYTHONPATH="src/holosoma_inference:src/holosoma${PYTHONPATH:+:$PYTHONPATH}"
export SIM_CLOCK_PORT="${SIM_CLOCK_PORT:-5655}"
export SIM_STATE_PORT="${SIM_STATE_PORT:-5657}"
export PERCEPTION_OBS_PORT="${PERCEPTION_OBS_PORT:-5658}"
export SIM_CONTROL_PORT="${SIM_CONTROL_PORT:-5659}"
export SPARSE_ROOT_COMMAND_PORT="${SPARSE_ROOT_COMMAND_PORT:-5661}"
export PERCEPTION_OBS_SHM_NAME="${PERCEPTION_OBS_SHM_NAME:-depth_img_shm_${SIM_STATE_PORT}}"
export HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_ROOT_STATE_ASSIST:-0}"
export HOLOSOMA_POLICY_TARGET_ROBOT_DOF_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_ROBOT_DOF_STATE_ASSIST:-0}"
export HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST="${HOLOSOMA_POLICY_TARGET_OBJECT_STATE_ASSIST:-0}"
export HOLOSOMA_POLICY_TTY_INPUT="${HOLOSOMA_POLICY_TTY_INPUT:-1}"
export HOLOSOMA_KEYBOARD_ROOT_COMMAND="${HOLOSOMA_KEYBOARD_ROOT_COMMAND:-1}"
export HOLOSOMA_SKIP_STIFF_PROMPT="${HOLOSOMA_SKIP_STIFF_PROMPT:-1}"
