#!/usr/bin/env bash
set -euo pipefail

SIM2SIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SIM2SIM_DIR}/.." && pwd)"
cd "$ROOT_DIR"

if [[ $# -eq 0 ]]; then
  set -- box_75
fi

: "${SIM2SIM_POLICY_NAME:?SIM2SIM_POLICY_NAME is required}"
: "${SIM2SIM_MODEL_REF:?SIM2SIM_MODEL_REF is required}"
: "${SIM2SIM_INFERENCE_CONFIG:?SIM2SIM_INFERENCE_CONFIG is required}"

export DEFAULT_MODEL_INPUT="${DEFAULT_MODEL_INPUT:-${SIM2SIM_MODEL_REF}}"
export MODEL_INPUT="${MODEL_INPUT:-${MODEL_PATH:-${MODEL_REF:-${SIM2SIM_MODEL_REF}}}}"
export INFERENCE_CONFIG="${INFERENCE_CONFIG:-${SIM2SIM_INFERENCE_CONFIG}}"

export COMMAND_WEB="${COMMAND_WEB:-0}"
export COMMAND_WEB_TRACK_ONLY="${COMMAND_WEB_TRACK_ONLY:-0}"
export MJ_ENV_AUTO_LAUNCH_POLICY="${MJ_ENV_AUTO_LAUNCH_POLICY:-1}"
export POLICY_AUTO_START_MOTION_CLIP="${POLICY_AUTO_START_MOTION_CLIP:-0}"
export SIM_MOTION_INIT_MODE="${SIM_MOTION_INIT_MODE:-training_default_pose}"
export POLICY_STDIO="${POLICY_STDIO:-inherit}"
export HOLOSOMA_KEYBOARD_ROOT_COMMAND="${HOLOSOMA_KEYBOARD_ROOT_COMMAND:-1}"
export HOLOSOMA_KEYBOARD_ROOT_COMMAND_MODE="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_MODE:-manual}"
export HOLOSOMA_KEYBOARD_ROOT_COMMAND_INPUT_MODE="${HOLOSOMA_KEYBOARD_ROOT_COMMAND_INPUT_MODE:-hold}"
export HOLOSOMA_MUJOCO_BACKSPACE_POLICY_CONTROL="${HOLOSOMA_MUJOCO_BACKSPACE_POLICY_CONTROL:-1}"
export HOLOSOMA_MUJOCO_BACKSPACE_AUTORESTART_POLICY="${HOLOSOMA_MUJOCO_BACKSPACE_AUTORESTART_POLICY:-1}"
export HOLOSOMA_MUJOCO_GUARD_DEFAULT_RESET="${HOLOSOMA_MUJOCO_GUARD_DEFAULT_RESET:-1}"

echo "[INFO] _sim2sim policy=${SIM2SIM_POLICY_NAME}"
echo "[INFO] _sim2sim model=${MODEL_INPUT}"
echo "[INFO] _sim2sim inference_config=${INFERENCE_CONFIG}"

exec bash "$ROOT_DIR/mj_env.sh" "$@"
