#!/usr/bin/env bash
set -euo pipefail

# Contact-aware ablation on top of W&B run c1gaknfu / w5qostjn_linvel.
# The intended diff from c1gaknfu is only:
#   - actor_obs_root -> actor_obs_root_contact_aware
#   - ROOT_COMMAND_MODE=contact-aware with the contact-aware carry-window mask
#
# Usage:
#   bash _scripts_gen_debug/debug_c1g_contact_aware.sh [extra distill_box_perception.sh args...]
#
# Optional env:
#   RUN_NAME=...                    W&B run name.
#   TOTAL_NUM_ENVS=32768            Global env count. With 8 ranks this is 4096 envs/rank.
#   TEACHER_CHECKPOINT=...          Defaults to local model_17000.pt if present, else wandb URI.
#   STUDENT_ACTOR_INPUTS=...        Override only if you intentionally want a non-strict ablation.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)

LOCAL_TEACHER_CHECKPOINT="${REPO_DIR}/.teacher_checkpoints/model_17000.pt"
if [[ -z "${TEACHER_CHECKPOINT:-}" ]]; then
  if [[ -f "${LOCAL_TEACHER_CHECKPOINT}" ]]; then
    TEACHER_CHECKPOINT="${LOCAL_TEACHER_CHECKPOINT}"
  else
    TEACHER_CHECKPOINT="wandb://zihanw22/boxer/u5lguxvl/model_17000.pt"
  fi
fi

export RUN_NAME="${RUN_NAME:-w5qostjn_linvel_contact_aware}"
export DATA_MODE="${DATA_MODE:-pure-sd}"
export TRACKER_PROFILE="${TRACKER_PROFILE:-old-tracker}"
export SCHEDULE_VARIANT="${SCHEDULE_VARIANT:-ppo_first}"
export ROOT_COMMAND_MODE="${ROOT_COMMAND_MODE:-contact-aware}"
export EXP="${EXP:-g1-29dof-wbt-w-object-distill-sparse-root-cmd-r2s-rollout-ref-shoo7sr1-contact-aware-debug}"
export TRAINING_NAME="${TRAINING_NAME:-g1_29dof_wbt_w_object_distill_box_perception_sparse_root_cmd_r2s_rollout_ref_access_to_depth}"
export TRAINING_PROJECT="${TRAINING_PROJECT:-boxer}"

export MOTION_DIR="${MOTION_DIR:-${REPO_DIR}/outputs/motion_bank_success_box_0_92_0p3}"
export ADAPTIVE_SAMPLING_CONTACT_INTERVAL_ROOT="${ADAPTIVE_SAMPLING_CONTACT_INTERVAL_ROOT:-${REPO_DIR}/outputs/clips}"

export TOTAL_NUM_ENVS="${TOTAL_NUM_ENVS:-32768}"
export DEFAULT_ENVS_PER_GPU="${DEFAULT_ENVS_PER_GPU:-4096}"
export NUM_LEARNING_ITERATIONS="${NUM_LEARNING_ITERATIONS:-20001}"
export SAVE_INTERVAL="${SAVE_INTERVAL:-500}"

export ACTOR_LR="${ACTOR_LR:-7e-5}"
export CRITIC_LR="${CRITIC_LR:-7e-5}"
export INIT_NOISE_STD="${INIT_NOISE_STD:-0.01}"
export ACTOR_MIN_NOISE_STD="${ACTOR_MIN_NOISE_STD:-0.01}"
export ENTROPY_COEF="${ENTROPY_COEF:-0.0}"

export TEACHER_COMPAT_PROFILE="${TEACHER_COMPAT_PROFILE:-u5lguxvl_generalist}"
export TEACHER_OBS_KEYS="${TEACHER_OBS_KEYS:-actor_obs}"
export TEACHER_PERCEPTION_PRESET="${TEACHER_PERCEPTION_PRESET:-none}"
export TEACHER_PERCEPTION_OBS_KEY="${TEACHER_PERCEPTION_OBS_KEY:-}"
export TEACHER_ACTOR_OBS_HISTORY_LENGTH="${TEACHER_ACTOR_OBS_HISTORY_LENGTH:-5}"
export CRITIC_PERCEPTION_PRESET="${CRITIC_PERCEPTION_PRESET:-none}"
export CRITIC_PERCEPTION_OBS_KEY="${CRITIC_PERCEPTION_OBS_KEY:-critic_perception_obs}"
export PERCEPTION_INTO_CRITIC_MODULES="${PERCEPTION_INTO_CRITIC_MODULES:-False}"

export STUDENT_ACTOR_INPUTS="${STUDENT_ACTOR_INPUTS:-['actor_obs_root_contact_aware','actor_obs_proprio']}"
export STUDENT_PROPRIO_HISTORY_LENGTH="${STUDENT_PROPRIO_HISTORY_LENGTH:-5}"
export CRITIC_PROPRIO_HISTORY_LENGTH="${CRITIC_PROPRIO_HISTORY_LENGTH:-5}"

export PPO_START_EPOCH="${PPO_START_EPOCH:-0}"
export DAGGER_END_EPOCH="${DAGGER_END_EPOCH:-4000}"
export PPO_START_COEFF="${PPO_START_COEFF:-0.1}"
export PPO_TARGET_COEFF="${PPO_TARGET_COEFF:-0.9}"
export PPO_SCHEDULE_STEP_EPOCHS="${PPO_SCHEDULE_STEP_EPOCHS:-500}"
export DAGGER_LOSS_COEF="${DAGGER_LOSS_COEF:-1.0}"
export DAGGER_MATCH_STD="${DAGGER_MATCH_STD:-True}"
export BC_LOSS_COEF="${BC_LOSS_COEF:-1.0}"
export PPO_START_NOISE_STD="${PPO_START_NOISE_STD:-0.1}"
export PPO_START_NOISE_STD_UNTIL_COEFF="${PPO_START_NOISE_STD_UNTIL_COEFF:-0.1}"
export TEACHER_ACTION_MIX_RATIO="${TEACHER_ACTION_MIX_RATIO:-0.0}"

export SCHEDULE_NAME="${SCHEDULE_NAME:-sparse_root_teacher_anchor_v4_ppo_first_step_mix_contact_aware}"
export SCHEDULE_NOTES="${SCHEDULE_NOTES:-c1gaknfu / w5qostjn_linvel contact-aware ablation: same teacher, data, PPO-first schedule, depth perception, history, and sampling; actor root command is contact-aware masked.}"
export DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES="${DAGGER_IGNORE_EXTERNAL_GOAL_SAMPLES:-False}"
export DAGGER_IGNORE_EPISODE_INITIAL_STEPS="${DAGGER_IGNORE_EPISODE_INITIAL_STEPS:-0}"
export FIXED_BC_EVAL_LOG_INTERVAL="${FIXED_BC_EVAL_LOG_INTERVAL:-1000}"

export USE_ADAPTIVE_TIMESTEPS_SAMPLER="${USE_ADAPTIVE_TIMESTEPS_SAMPLER:-True}"
export CONTACT_AWARE_CARRY_WINDOW_MODE="${CONTACT_AWARE_CARRY_WINDOW_MODE:-peak_height}"
export CONTACT_AWARE_PEAK_HEIGHT_ALPHA="${CONTACT_AWARE_PEAK_HEIGHT_ALPHA:-0.91}"
export CONTACT_AWARE_PEAK_HEIGHT_SMOOTHING_STEPS="${CONTACT_AWARE_PEAK_HEIGHT_SMOOTHING_STEPS:-5}"
export UNIFORM_T1_WINDOW_SAMPLING_ENABLED="${UNIFORM_T1_WINDOW_SAMPLING_ENABLED:-False}"
export UNIFORM_T1_WINDOW_HALF_WIDTH_STEPS="${UNIFORM_T1_WINDOW_HALF_WIDTH_STEPS:-50}"
export UNIFORM_T1_WINDOW_DENSITY_BOOST="${UNIFORM_T1_WINDOW_DENSITY_BOOST:-1.0}"
export START_AT_TIMESTEP_ZERO_PROB="${START_AT_TIMESTEP_ZERO_PROB:-0.2}"
export START_AT_TIMESTEP_ZERO_PROB_END="${START_AT_TIMESTEP_ZERO_PROB_END:-None}"
export START_AT_TIMESTEP_ZERO_PROB_START_ITER="${START_AT_TIMESTEP_ZERO_PROB_START_ITER:-None}"
export START_AT_TIMESTEP_ZERO_PROB_END_ITER="${START_AT_TIMESTEP_ZERO_PROB_END_ITER:-None}"
export FREEZE_AT_TIMESTEP_ZERO_PROB="${FREEZE_AT_TIMESTEP_ZERO_PROB:-0.0}"
export FREEZE_AT_TIMESTEP_ZERO_PROB_END="${FREEZE_AT_TIMESTEP_ZERO_PROB_END:-0.0}"
export FREEZE_AT_TIMESTEP_ZERO_PROB_START_ITER="${FREEZE_AT_TIMESTEP_ZERO_PROB_START_ITER:-2500}"
export FREEZE_AT_TIMESTEP_ZERO_PROB_END_ITER="${FREEZE_AT_TIMESTEP_ZERO_PROB_END_ITER:-10000}"

export SPARSE_GOAL_ENABLED="${SPARSE_GOAL_ENABLED:-False}"
export CLIP_GOAL_DELTA_MIN_STEPS="${CLIP_GOAL_DELTA_MIN_STEPS:-60}"
export CLIP_GOAL_DELTA_MAX_STEPS="${CLIP_GOAL_DELTA_MAX_STEPS:-180}"
export COMMAND_ONLY_ENV_PROB_START="${COMMAND_ONLY_ENV_PROB_START:-0.0}"
export COMMAND_ONLY_ENV_PROB_END="${COMMAND_ONLY_ENV_PROB_END:-0.0}"
export COMMAND_ONLY_ENV_PROB_START_ITER="${COMMAND_ONLY_ENV_PROB_START_ITER:-None}"
export COMMAND_ONLY_ENV_PROB_END_ITER="${COMMAND_ONLY_ENV_PROB_END_ITER:-None}"
export EVAL_COMMAND_ONLY_ENV_PROB="${EVAL_COMMAND_ONLY_ENV_PROB:-None}"
export EXTERNAL_GOAL_PROB_START="${EXTERNAL_GOAL_PROB_START:-0.0}"
export EXTERNAL_GOAL_PROB_END="${EXTERNAL_GOAL_PROB_END:-1.0}"
export EXTERNAL_GOAL_PROB_START_ITER="${EXTERNAL_GOAL_PROB_START_ITER:-None}"
export EXTERNAL_GOAL_PROB_END_ITER="${EXTERNAL_GOAL_PROB_END_ITER:-None}"
export EXTERNAL_GOAL_PROB_RAMP_RESETS="${EXTERNAL_GOAL_PROB_RAMP_RESETS:-200000}"
export EVAL_EXTERNAL_GOAL_PROB="${EVAL_EXTERNAL_GOAL_PROB:-None}"
export EXTERNAL_GOAL_RANGE_RAMP_RESETS="${EXTERNAL_GOAL_RANGE_RAMP_RESETS:-None}"
export EXTERNAL_GOAL_RANGE_START_ITER="${EXTERNAL_GOAL_RANGE_START_ITER:-None}"
export EXTERNAL_GOAL_RANGE_END_ITER="${EXTERNAL_GOAL_RANGE_END_ITER:-None}"
export EXTERNAL_GOAL_SAMPLING_MODE="${EXTERNAL_GOAL_SAMPLING_MODE:-box}"
export EXTERNAL_GOAL_RADIUS_MIN_START="${EXTERNAL_GOAL_RADIUS_MIN_START:-None}"
export EXTERNAL_GOAL_RADIUS_MAX_START="${EXTERNAL_GOAL_RADIUS_MAX_START:-None}"
export EXTERNAL_GOAL_RADIUS_MIN="${EXTERNAL_GOAL_RADIUS_MIN:-1.0}"
export EXTERNAL_GOAL_RADIUS_MAX="${EXTERNAL_GOAL_RADIUS_MAX:-3.4}"
export EXTERNAL_GOAL_POS_LOCAL_MIN_START="${EXTERNAL_GOAL_POS_LOCAL_MIN_START:-None}"
export EXTERNAL_GOAL_POS_LOCAL_MAX_START="${EXTERNAL_GOAL_POS_LOCAL_MAX_START:-None}"
export EXTERNAL_GOAL_POS_LOCAL_MIN="${EXTERNAL_GOAL_POS_LOCAL_MIN:-[1.0, -0.8, 0.7]}"
export EXTERNAL_GOAL_POS_LOCAL_MAX="${EXTERNAL_GOAL_POS_LOCAL_MAX:-[1.75, 0.8, 1.0]}"

export PERCEPTION_PRESET="${PERCEPTION_PRESET:-camera_depth_d435i}"
export IMAGE_WIDTH="${IMAGE_WIDTH:-106}"
export IMAGE_HEIGHT="${IMAGE_HEIGHT:-60}"
export CAMERA_PITCH_DEG="${CAMERA_PITCH_DEG:-10}"
export CAMERA_FAR="${CAMERA_FAR:-3.0}"
export CAMERA_MAX_DISTANCE="${CAMERA_MAX_DISTANCE:-3.0}"
export PERCEPTION_WARP_PREPROCESS="${PERCEPTION_WARP_PREPROCESS:-True}"
export CAMERA_APPLY_SENSOR_NOISE="${CAMERA_APPLY_SENSOR_NOISE:-False}"
export OBJECT_GEOMETRY_MODE="${OBJECT_GEOMETRY_MODE:-default}"

export PAIR_TERRAIN_WITH_MOTION="${PAIR_TERRAIN_WITH_MOTION:-False}"
export RESET_TO_DEFAULT_POSE="${RESET_TO_DEFAULT_POSE:-False}"
export ENABLE_DEFAULT_POSE_PREPEND="${ENABLE_DEFAULT_POSE_PREPEND:-False}"
export DEFAULT_POSE_PREPEND_DURATION_S="${DEFAULT_POSE_PREPEND_DURATION_S:-0.0}"
export ENABLE_DEFAULT_POSE_APPEND="${ENABLE_DEFAULT_POSE_APPEND:-False}"
export DEFAULT_POSE_APPEND_DURATION_S="${DEFAULT_POSE_APPEND_DURATION_S:-0.0}"
export MAX_EPISODE_LENGTH_S="${MAX_EPISODE_LENGTH_S:-8.0}"

export PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY="${PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY:-134217728}"
export PHYSX_GPU_FOUND_LOST_AGGREGATE_PAIRS_CAPACITY="${PHYSX_GPU_FOUND_LOST_AGGREGATE_PAIRS_CAPACITY:-134217728}"
export PHYSX_GPU_TOTAL_AGGREGATE_PAIRS_CAPACITY="${PHYSX_GPU_TOTAL_AGGREGATE_PAIRS_CAPACITY:-16777216}"
export PHYSX_GPU_COLLISION_STACK_SIZE="${PHYSX_GPU_COLLISION_STACK_SIZE:-268435456}"

exec bash "${REPO_DIR}/distill_box_perception.sh" \
  pure-sd \
  ppo-first \
  "${RUN_NAME}" \
  "${TEACHER_CHECKPOINT}" \
  --command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-lin-vel="[0.5, 0.5, 0.2]" \
  --command.setup-terms.motion-command.params.motion-config.noise-to-initial-pose.root-ang-vel="[0.52, 0.52, 0.78]" \
  "$@"
